### ISSUE TITLE
SFSafariViewController does not authenticate the user

### ISSUE THREAD

**Issue by mertkgs** [microsoft/appcenter-sdk-apple#1795] opened 2019-09-26 18:38 UTC
### **Description**

We use MSDistribute for our in-house app to be able to provide in-app updates. While we are testing our app we had faced issue which is when we install and open the app, SFSafariViewController navigate to install.appcenter.com and 'in-app updates enabled' written with count down 'returning to app in 3...' -2-1 and then it stays. This safari window does not close automatically. there is a blue button which is written as 'return the app now' but it doesn't work either.
As a result we can't navigate back to app with success authentication. we can't push the updates

We faced this issue first on iOS 9.0 and we tested also on device with iOS 10.2.1 and same problem occurred. When we quit the app and re-open it, same issue occur again.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Installing the app from install.appcenter.com
2. Run it.

### **Details**

1. Which SDK version are you using?
    - 2.3.0
2. Which OS version did you experience the issue on?
    -  iOS 9.0 , 10.2.1 / Xcode 10 - Xcode 11
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.8.0 , 1.7.5
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPad Air , iPad Pro
5. What language are you using?
    - [x] Objective C

**Comment by annakocheshkova** [comment] 2019-09-27 09:26
Hi there, could you provide verbose logs please?
Has it ever worked for you or stopped working at some point?

**Comment by mertkgs** [comment] 2019-09-27 10:20
> Hi there, could you provide verbose logs please?
> Has it ever worked for you or stopped working at some point?

Hi Anna,
It is working on our iOS 12 devices as expected. But it has never worked and stuck on that authentication process as mentioned OS versions. 

Those are remote devices so we can not attach those to our dev platform. 
could you help me to how to get verbose logs?
Thank you.

**Comment by annakocheshkova** [comment] 2019-09-27 16:53
We can't reproduce this on our devices. Do you have [this section](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios#23-modify-the-projects-infoplist) properly configured?

**Comment by AnastasiaKubova** [comment] 2019-10-02 06:07
I am closing this issue. Feel free to reopen if you feel like you need support.

**Closed by AnastasiaKubova** 2019-10-02 06:07 UTC
