### ISSUE TITLE
macOS frameworks contain several copies of binaries

### ISSUE THREAD

**Issue by al-skobelev** [microsoft/appcenter-sdk-apple#1938] opened 2019-12-30 10:41 UTC
### **Description**

The binary distribution of AppCenter SDK should have soft links to real files in the framework s roots. Currently it doesn't and contains real files instead,  so it triples the size required for the frameworks. It should keep the real data in the Versions/A folder, the folder Versions/Curren should be a soft link to Versions/A, the Headers, Modules, Resources folders, and a frameworks binary in the frameworks root should be soft links to the corresponding items in the Versions/A folder.

**Comment by al-skobelev** [comment] 2019-12-30 11:42
I suggest you need use -y option when creating a zip archive to keep symlinks.

**Comment by MatkovIvan** [comment] 2019-12-30 12:15
Hi @al-skobelev ,
Thanks for getting in touch!

Currently the archives don't contains duplicates that increase size. Please note that it's a **static** frameworks, so it shouldn't be embedded.

Closing this one since it's duplicate of #1296 and #1925

**Comment by al-skobelev** [comment] 2019-12-30 19:22
Hi @MatkovIvan they don't increase the size of an application, but increase it in sources on my disk and in repository (ok I removed them manually to not have duplicates). In any case it looks weird. What is the reason you create them in that way?

**Comment by MatkovIvan** [comment] 2020-01-03 13:56
See @jwallra's explanation in the original thread: https://github.com/microsoft/appcenter/issues/1296#issuecomment-542938541

**Comment by al-skobelev** [comment] 2020-01-03 15:29
@MatkovIvan, I can see there an explanation why you use static framework. But I can not find one for why you place there several copies of binaries and executables. 
Why don't just remove the Versions subfolder from the framework in distribution? You don't need it at all.

**Comment by MatkovIvan** [comment] 2020-01-06 08:46
@al-skobelev you are right, I see the duplicates in macOS frameworks. I accidentally checked only iOS frameworks because there was no mention that this issue is macOS specific. 

Thanks for reporting.

**Comment by al-skobelev** [comment] 2020-01-09 07:53
@MatkovIvan, thank you!

**Comment by annakocheshkova** [comment] 2020-02-17 10:00
Hi there! This issue has been fixed in the [3.0.0 release](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/3.0.0). Please check it and reopen in case there are any issues.

**Closed by annakocheshkova** 2020-02-17 10:00 UTC
Labels: bug
