### ISSUE TITLE
Appcenter events not showing for some devices

### ISSUE THREAD

**Issue by aatanac** [microsoft/appcenter-sdk-apple#2268] opened 2021-02-10 17:12 UTC
### **Description**

Events are not showing in AppCenter events tab on some devices. Tested with multiple different devices, with same iOS, was not working on two device iPhoneX 14.4 and iPhone 8 13.0. App is already using in production AppCenter for logging and we did not notice this behaviour before.
Did you had similar issues earlier? Could not find them
As I see from logs receiving multiple times 400 error on trying to send logs to server

This is implementation, nothing special here

        AppCenter.logLevel = .verbose
        AppCenter.start(withAppSecret: self.secret, services: [Distribute.self, Crashes.self, Analytics.self])
        Crashes.enabled = self.isTracking
        Analytics.enabled = self.isTracking
        
Thank you

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.Install clean build(could be adHoc or dev build from XCode does not matter)
2.Open app
3. Start AppCenter SDK with secret key and services Distribute, Crashes, Analytics

### **Details**

1. Which SDK version are you using?
    - 4.0.0
2. Which OS version did you experience the issue on?
    - 14.4, 13.0, on others worked
3. Which Cocoapods version are you using (run `pod --version`)?
    - e.g. 1.10.1
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    -  iPhone8, iPhoneX
5. What language are you using?
    - [x] Swift
6. What third party libraries are you using? 
AppCenter, Firebase, Alamofire...
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

2021-03-18 18:05:26.288231+0100 Energy Buddy[495:24118] [AppCenter] VERBOSE: -[MSACDelegateForwarder addTraceBlock:]_block_invoke_2/88 Start buffering traces.
2021-03-18 18:05:26.288460+0100 Energy Buddy[495:24118] [AppCenter] DEBUG: -[MSACDelegateForwarder setEnabledFromPlistForKey:]_block_invoke/278 Delegate forwarder for info.plist key 'AppCenterAppDelegateForwarderEnabled' enabled. It may use swizzling.
2021-03-18 18:05:26.288633+0100 Energy Buddy[495:24118] [AppCenter] DEBUG: -[MSACDelegateForwarder swizzleOriginalSelector:withCustomSelector:originalClass:]_block_invoke/205 Selector 'setDelegate:' of class 'UIApplication' is swizzled.
2021-03-18 18:05:26.288772+0100 Energy Buddy[495:24118] [AppCenter] DEBUG: -[MSACDelegateForwarder swizzleOriginalSelector:withCustomSelector:originalClass:]_block_invoke/205 Selector 'application:openURL:options:' of class 'Coneva.AppDelegate' is swizzled.
2021-03-18 18:05:26.288935+0100 Energy Buddy[495:24118] [AppCenter] VERBOSE: +[MSACDelegateForwarder flushTraceBuffer]/106 Stop buffering traces, flushed.
2021-03-18 18:05:26.290754+0100 Energy Buddy[495:24118] [AppCenter] VERBOSE: -[MSACSessionContext setSessionId:]/66 Stored new session with id:(null) and timestamp: 2021-03-18 17:05:26 +0000.
2021-03-18 18:05:26.291389+0100 Energy Buddy[495:24118] [AppCenter] DEBUG: -[MSACUserIdContext init]/54 0 userId(s) in the history.
2021-03-18 18:05:26.293705+0100 Energy Buddy[495:24118] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-03-18 18:05:26.297272+0100 Energy Buddy[495:24118] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-03-18 18:05:26.297396+0100 Energy Buddy[495:24118] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-03-18 18:05:26.297602+0100 Energy Buddy[495:24118] [AppCenter] DEBUG: -[MSACDBStorage initWithSchema:version:filename:]_block_invoke/31 SQLite global configuration successfully updated.
2021-03-18 18:05:26.302961+0100 Energy Buddy[495:24118] [AppCenter] INFO: -[MSACDBStorage configureDatabaseWithSchema:version:filename:]/85 Created "Logs.sqlite" database with 5 version.
2021-03-18 18:05:26.304268+0100 Energy Buddy[495:24118] [AppCenter] DEBUG: +[MSACDBStorage enableAutoVacuumInOpenedDatabase:]/272 Vacuuming database and enabling auto_vacuum
2021-03-18 18:05:26.307802+0100 Energy Buddy[495:24118] [AppCenter] INFO: -[MSACAppCenter configureWithAppSecret:transmissionTargetToken:fromApplication:]/350 App Center SDK configured successfully.
2021-03-18 18:05:26.308021+0100 Energy Buddy[495:24118] [AppCenter] VERBOSE: -[MSACAppCenterUserDefaults migrateKeys:forService:]/35 Migrating the old NSDefaults keys to new ones.
2021-03-18 18:05:26.309125+0100 Energy Buddy[495:24118] [AppCenterDistribute] INFO: -[MSACDistribute init]/126 Delete update token if exists.
2021-03-18 18:05:26.310055+0100 Energy Buddy[495:24118] [AppCenter] WARNING: +[MSACKeychainUtil stringForKey:withServiceName:statusCode:]/85 Failed to retrieve item with key='MSUpdateToken', service='de.coneva.energy.dev.AppCenter' from keychain. OS Status code -25300
2021-03-18 18:05:26.311142+0100 Energy Buddy[495:24118] [AppCenter] VERBOSE: -[MSACAppCenterUserDefaults migrateKeys:forService:]/35 Migrating the old NSDefaults keys to new ones.
2021-03-18 18:05:26.316971+0100 Energy Buddy[495:24118] [AppCenter] VERBOSE: -[MSACAppCenter startServices:withAppSecret:transmissionTargetToken:fromApplication:]/376 Start services MSACCrashes, MSACDistribute, MSACAnalytics from an application
2021-03-18 18:05:26.317639+0100 Energy Buddy[495:24118] [AppCenterCrashes] DEBUG: -[MSACCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/691 EnableUncaughtExceptionHandler is set to YES
2021-03-18 18:05:26.317696+0100 Energy Buddy[495:24118] [AppCenterCrashes] VERBOSE: -[MSACCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/701 Enabled Mach exception handler.
2021-03-18 18:05:26.331243+0100 Energy Buddy[495:24118] [AppCenterCrashes] WARNING: -[MSACCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/715 Detecting crashes is NOT enabled due to running the app with a debugger attached.
2021-03-18 18:05:26.338798+0100 Energy Buddy[495:24472] [Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 87 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 87 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}
2021-03-18 18:05:26.339973+0100 Energy Buddy[495:24118] [AppCenter] VERBOSE: -[MSACSessionContext clearSessionHistoryAndKeepCurrentSession:]/88 Cleared old sessions.
2021-03-18 18:05:26.340122+0100 Energy Buddy[495:24118] [AppCenter] VERBOSE: -[MSACUserIdContext clearUserIdHistory]/125 Cleared old userIds while keeping current userId.
2021-03-18 18:05:26.340166+0100 Energy Buddy[495:24118] [AppCenterCrashes] INFO: -[MSACCrashes applyEnabledState:]/436 Crashes service has been enabled but the service cannot detect crashes due to running the application with a debugger attached.
2021-03-18 18:05:26.346082+0100 Energy Buddy[495:24118] [AppCenterCrashes] VERBOSE: -[MSACCrashes startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]/483 Started crash service.
2021-03-18 18:05:26.346577+0100 Energy Buddy[495:24118] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-03-18 18:05:26.346620+0100 Energy Buddy[495:24118] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-03-18 18:05:26.346654+0100 Energy Buddy[495:24118] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-03-18 18:05:26.346814+0100 Energy Buddy[495:24118] [AppCenterDistribute] INFO: -[MSACDistribute applyEnabledState:]/185 Distribute service has been enabled.
2021-03-18 18:05:26.347848+0100 Energy Buddy[495:24118] [AppCenter] WARNING: +[MSACKeychainUtil stringForKey:withServiceName:statusCode:]/85 Failed to retrieve item with key='MSUpdateToken', service='de.coneva.energy.dev.AppCenter' from keychain. OS Status code -25300
2021-03-18 18:05:26.347942+0100 Energy Buddy[495:24118] [AppCenterDistribute] DEBUG: -[MSACDistribute checkLatestRelease:distributionGroupId:releaseHash:]/586 Distribute won't check if a new release is available because of one of the following reasons: 1. A debugger is attached. 2. You are running the debug configuration. 3. The app is running in a non-adhoc environment. Detach the debugger and restart the app and/or run the app with the release configuration to enable the feature.
2021-03-18 18:05:26.347976+0100 Energy Buddy[495:24118] [AppCenterDistribute] VERBOSE: -[MSACDistribute startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]/284 Started Distribute service.
2021-03-18 18:05:26.348184+0100 Energy Buddy[495:24472] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/493 Identifying object <MSACAnalytics: 0x282ebad90> removed from pause lane for channel Analytics.
2021-03-18 18:05:26.348235+0100 Energy Buddy[495:24472] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/495 Resume channel Analytics.
2021-03-18 18:05:26.348292+0100 Energy Buddy[495:24472] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/493 Identifying object <MSACAnalytics: 0x282ebad90> removed from pause lane for channel Analytics/one.
2021-03-18 18:05:26.348324+0100 Energy Buddy[495:24472] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/495 Resume channel Analytics/one.
2021-03-18 18:05:26.348973+0100 Energy Buddy[495:24118] [AppCenter] VERBOSE: -[MSACSessionContext setSessionId:]/66 Stored new session with id:C3A332EB-AB3C-4924-9499-DF9078F85B9B and timestamp: 2021-03-18 17:05:26 +0000.
2021-03-18 18:05:26.349011+0100 Energy Buddy[495:24118] [AppCenterAnalytics] INFO: -[MSACSessionTracker renewSessionId]/49 New session ID: C3A332EB-AB3C-4924-9499-DF9078F85B9B
2021-03-18 18:05:26.349467+0100 Energy Buddy[495:24118] [AppCenterCrashes] VERBOSE: -[MSACCrashes channel:didPrepareLog:internalId:flags:]/566 Storing a log to Crashes Buffer: (sid: C3A332EB-AB3C-4924-9499-DF9078F85B9B, type: startSession)
2021-03-18 18:05:26.349508+0100 Energy Buddy[495:24118] [AppCenterCrashes] VERBOSE: -[MSACCrashes channel:didPrepareLog:internalId:flags:]/577 Found an empty buffer position.
2021-03-18 18:05:26.349586+0100 Energy Buddy[495:24472] [AppCenter] DEBUG: -[MSACChannelUnitDefault enqueueItem:flags:]_block_invoke/155 Saving log, type: startSession, flags: 1.
2021-03-18 18:05:26.349603+0100 Energy Buddy[495:24118] [AppCenterAnalytics] INFO: -[MSACAnalytics applyEnabledState:]/182 Analytics service has been enabled.
2021-03-18 18:05:26.349679+0100 Energy Buddy[495:24118] [AppCenterAnalytics] VERBOSE: -[MSACAnalytics startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]/133 Started Analytics service.
2021-03-18 18:05:26.349886+0100 Energy Buddy[495:24118] [AppCenterCrashes] VERBOSE: -[MSACCrashes channel:didPrepareLog:internalId:flags:]/566 Storing a log to Crashes Buffer: (sid: (null), type: startService)
2021-03-18 18:05:26.349922+0100 Energy Buddy[495:24118] [AppCenterCrashes] VERBOSE: -[MSACCrashes channel:didPrepareLog:internalId:flags:]/589 Remembering index 0 for oldest timestamp 1616087126.349502.
2021-03-18 18:05:26.349950+0100 Energy Buddy[495:24118] [AppCenterCrashes] VERBOSE: -[MSACCrashes channel:didPrepareLog:internalId:flags:]/577 Found an empty buffer position.
2021-03-18 18:05:26.351268+0100 Energy Buddy[495:24472] [AppCenter] VERBOSE: -[MSACLogDBStorage saveLog:withGroupId:flags:]_block_invoke/130 Log is stored with id: '1'
2021-03-18 18:05:26.351409+0100 Energy Buddy[495:24472] [AppCenterCrashes] VERBOSE: -[MSACCrashes channel:didCompleteEnqueueingLog:internalId:]/619 Deleting a log from buffer with id 96314D06-DDB6-4A19-A88D-18649FE35CE7
2021-03-18 18:05:26.351550+0100 Energy Buddy[495:24472] [AppCenter] DEBUG: -[MSACChannelUnitDefault enqueueItem:flags:]_block_invoke/155 Saving log, type: startService, flags: 1.
2021-03-18 18:05:26.353151+0100 Energy Buddy[495:24472] [AppCenter] VERBOSE: -[MSACLogDBStorage saveLog:withGroupId:flags:]_block_invoke/130 Log is stored with id: '2'
2021-03-18 18:05:26.353290+0100 Energy Buddy[495:24472] [AppCenterCrashes] VERBOSE: -[MSACCrashes channel:didCompleteEnqueueingLog:internalId:]/619 Deleting a log from buffer with id 34FF9FAB-59C3-4BCF-A619-AD180DB0CAF4
2021-03-18 18:05:29.503241+0100 Energy Buddy[495:24507] [AppCenter] VERBOSE: -[MSACLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:completionHandler:]/220 Load log(s) with id(s) '1' as batch Id:CEDE9EC0-98B0-4007-A797-4198E0796241
2021-03-18 18:05:29.505531+0100 Energy Buddy[495:24507] [AppCenter] DEBUG: -[MSACChannelUnitDefault sendLogContainer:]/190 Sending 1/1 log, group Id: Analytics, batch Id: CEDE9EC0-98B0-4007-A797-4198E0796241, session Id: C3A332EB-AB3C-4924-9499-DF9078F85B9B, payload:
{
  "sid" : "C3A332EB-AB3C-4924-9499-DF9078F85B9B",
  "timestamp" : "2021-03-18T17:05:26.349Z",
  "device" : {
    "screenSize" : "2436x1125",
    "appBuild" : "171",
    "osName" : "iOS",
    "timeZoneOffset" : 60,
    "carrierCountry" : "de",
    "osVersion" : "14.4",
    "carrierName" : "Telekom.de",
    "locale" : "en_DE",
    "appNamespace" : "de.coneva.energy.dev",
    "osBuild" : "18D52",
    "sdkName" : "appcenter.ios",
    "oemName" : "Apple",
    "model" : "iPhone10,6",
    "sdkVersion" : "4.0.0",
    "appVersion" : "1.5.2"
  },
  "type" : "startSession"
}
2021-03-18 18:05:29.506631+0100 Energy Buddy[495:24507] [AppCenter] VERBOSE: -[MSACAppCenterIngestion willSendHTTPRequestToURL:withHeaders:]/95 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2021-03-18 18:05:29.506945+0100 Energy Buddy[495:24507] [AppCenter] VERBOSE: -[MSACAppCenterIngestion willSendHTTPRequestToURL:withHeaders:]/96 Headers: Content-Type = application/json, App-Secret = ****************************1697c272, Install-ID = 85030ED3-868F-45B1-8DA3-75C559448FB0
2021-03-18 18:05:29.512445+0100 Energy Buddy[495:24507] [AppCenter] VERBOSE: -[MSACLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:completionHandler:]/220 Load log(s) with id(s) '2' as batch Id:FB729C46-A020-4C33-95C0-869F6B0BFB3E
2021-03-18 18:05:29.513186+0100 Energy Buddy[495:24507] [AppCenter] DEBUG: -[MSACChannelUnitDefault sendLogContainer:]/190 Sending 1/1 log, group Id: AppCenter, batch Id: FB729C46-A020-4C33-95C0-869F6B0BFB3E, session Id: (null), payload:
{
  "device" : {
    "screenSize" : "2436x1125",
    "appBuild" : "171",
    "osName" : "iOS",
    "timeZoneOffset" : 60,
    "carrierCountry" : "de",
    "osVersion" : "14.4",
    "carrierName" : "Telekom.de",
    "locale" : "en_DE",
    "appNamespace" : "de.coneva.energy.dev",
    "osBuild" : "18D52",
    "sdkName" : "appcenter.ios",
    "oemName" : "Apple",
    "model" : "iPhone10,6",
    "sdkVersion" : "4.0.0",
    "appVersion" : "1.5.2"
  },
  "timestamp" : "2021-03-18T17:05:26.350Z",
  "type" : "startService",
  "services" : [
    "Crashes",
    "Distribute",
    "Analytics"
  ]
}
2021-03-18 18:05:29.514055+0100 Energy Buddy[495:24507] [AppCenter] VERBOSE: -[MSACAppCenterIngestion willSendHTTPRequestToURL:withHeaders:]/95 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2021-03-18 18:05:29.514404+0100 Energy Buddy[495:24507] [AppCenter] VERBOSE: -[MSACAppCenterIngestion willSendHTTPRequestToURL:withHeaders:]/96 Headers: Content-Type = application/json, App-Secret = ****************************1697c272, Install-ID = 85030ED3-868F-45B1-8DA3-75C559448FB0
2021-03-18 18:05:35.658441+0100 Energy Buddy[495:24118] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2021-03-18 18:05:35.676861+0100 Energy Buddy[495:24118] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
2021-03-18 18:05:37.022532+0100 Energy Buddy[495:24466] [AppCenter] VERBOSE: -[MSACHttpIngestion printResponse:body:error:]/217 HTTP response received with status code: 400, payload:
{
  "status" : "NoValidLogsFoundInLogContainer",
  "correlationId" : "7b90c332-e2f3-4c1b-986a-13f27ebec756",
  "validDiagnosticsIds" : [

  ],
  "throttledDiagnosticsIds" : [

  ]
}
2021-03-18 18:05:37.023225+0100 Energy Buddy[495:24466] [AppCenter] INFO: -[MSACHttpClient pause]/214 Pause HTTP client.
2021-03-18 18:05:37.023672+0100 Energy Buddy[495:24309] [AppCenter] ERROR: -[MSACChannelUnitDefault sendLogContainer:]_block_invoke/229 Log(s) sent with failure, batch Id:CEDE9EC0-98B0-4007-A797-4198E0796241, status code:400
2021-03-18 18:05:37.023742+0100 Energy Buddy[495:24466] [AppCenter] DEBUG: -[MSACHttpIngestion printResponse:body:error:]/202 HTTP request error with code: 2, domain: com.Microsoft.AppCenter.ErrorDomain, description: The operation was canceled.
2021-03-18 18:05:37.025887+0100 Energy Buddy[495:24309] [AppCenter] ERROR: -[MSACChannelUnitDefault sendLogContainer:]_block_invoke/242 Fatal error encountered; shutting down channel unit with group ID Analytics
2021-03-18 18:05:37.026160+0100 Energy Buddy[495:24309] [AppCenter] ERROR: -[MSACChannelUnitDefault sendLogContainer:]_block_invoke/229 Log(s) sent with failure, batch Id:FB729C46-A020-4C33-95C0-869F6B0BFB3E, status code:0
2021-03-18 18:05:37.027185+0100 Energy Buddy[495:24309] [AppCenter] VERBOSE: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/478 Identifying object <MSACChannelUnitDefault: 0x2838e1aa0> added to pause lane for channel Analytics.
2021-03-18 18:05:37.029197+0100 Energy Buddy[495:24309] [AppCenter] DEBUG: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/480 Pause channel Analytics.
2021-03-18 18:05:37.030261+0100 Energy Buddy[495:24309] [AppCenter] DEBUG: -[MSACChannelUnitDefault setEnabled:andDeleteDataOnDisabled:]_block_invoke/435 Delete all logs for group Id Analytics
2021-03-18 18:05:37.037942+0100 Energy Buddy[495:24466] [AppCenter] DEBUG: -[MSACHttpClient requestCompletedWithHttpCall:data:response:error:]/136 HTTP call was canceled; do not process further.
2021-03-18 18:05:37.041511+0100 Energy Buddy[495:24507] Connection 14: unable to determine interface type without an established connection
2021-03-18 18:05:37.041721+0100 Energy Buddy[495:24507] Connection 14: unable to determine fallback status without a connection
2021-03-18 18:05:37.042540+0100 Energy Buddy[495:24309] [AppCenter] VERBOSE: +[MSACLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/357 Deletion of log(s) by id with value(s) '1' succeeded.
2021-03-18 18:05:37.046477+0100 Energy Buddy[495:24309] [AppCenter] VERBOSE: +[MSACLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/357 Deletion of log(s) by groupId with value(s) 'Analytics' succeeded.
2021-03-18 18:05:37.047249+0100 Energy Buddy[495:24309] [AppCenter] VERBOSE: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/478 Identifying object <MSACChannelUnitDefault: 0x2838e1aa0> added to pause lane for channel Analytics/one.
2021-03-18 18:05:37.047477+0100 Energy Buddy[495:24309] [AppCenter] DEBUG: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/480 Pause channel Analytics/one.
2021-03-18 18:05:37.047659+0100 Energy Buddy[495:24309] [AppCenter] VERBOSE: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/478 Identifying object <MSACChannelUnitDefault: 0x2838e1c20> added to pause lane for channel Analytics/one.
2021-03-18 18:05:37.047792+0100 Energy Buddy[495:24309] [AppCenter] DEBUG: -[MSACChannelUnitDefault setEnabled:andDeleteDataOnDisabled:]_block_invoke/435 Delete all logs for group Id Analytics/one
2021-03-18 18:05:37.050586+0100 Energy Buddy[495:24309] [AppCenter] VERBOSE: +[MSACLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/357 Deletion of log(s) by groupId with value(s) 'Analytics/one' succeeded.

**Comment by Jamminroot** [comment] 2021-02-11 08:40
Hey @aatanac, thanks for reaching out and reporting this.

Can you kindly share a snippet of how you are sending an event? With the contents, too (if possible). 
If you are concerned about disclosing the contents of the event, you can also open a duplicate ticket through the App Center portal: 
Top-right corner, question mark -> Contact support. Select 'Analytics' in a dropdown and emphasize that the ticket is a duplicate of this issue.

**Comment by aatanac** [comment] 2021-02-11 09:04
Hi @Jamminroot 

Here is example of sending events 
```
let event = "REVIEW_TEASER_DISPLAYED_COUNT"
Analytics.trackEvent(event)
```

Problem is not only that we don't see events on some devices, STARTSERVICE and STARTSESSION are not also appearing in AppCenter Log flow. In some reason SDK requests are failing as you can see in logs above

**Comment by Jamminroot** [comment] 2021-02-12 07:36
Hm... The problem seem to be with the datetime on your device. Please fix those and issue should be resolved.

**Comment by Jamminroot** [comment] 2021-02-15 06:59
I'm closing the issue now, but please feel free to reopen if the issue remains.

**Closed by Jamminroot** 2021-02-15 06:59 UTC
Labels: support

**Comment by aatanac** [comment] 2021-02-15 14:57
@Jamminroot Issue was, as you mentioned, with date on our testing devices. 
Works fine now, thank you for help.
