### ISSUE TITLE
`MSCrashes.hasCrashedInLastSession()` is not `true` when the app was killed

### ISSUE THREAD

**Issue by sindresorhus** [microsoft/appcenter-sdk-apple#2155] opened 2020-08-27 22:18 UTC
### **Description**

I wanted to show a recovery message to users if my app crashed last time it was run, but I noticed it did not trigger when the app was killed.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add a `MSCrashes.hasCrashedInLastSession()` check.
2. Archive the app and then run it.
3. Kill it: `killall -TERM AppName`
4. Launch the app again.

### **Details**

1. Which SDK version are you using?
    - 3.3.3
2. Which OS version did you experience the issue on?
    - macOS 10.15.6
3. Which Cocoapods version are you using (run `pod --version`)?
    - None
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - MacBook Pro (16-inch, 2019)
5. What language are you using?
    - [ ] Objective C
    - [x] Swift
6. What third party libraries are you using?
	None
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

```
default	00:17:47.909200+0200	Recordia	[AppCenter] VERBOSE: -[MSDelegateForwarder addTraceBlock:]_block_invoke_2/88 Start buffering traces.
default	00:17:47.909266+0200	Recordia	[AppCenter] DEBUG: -[MSDelegateForwarder setEnabledFromPlistForKey:]_block_invoke/278 Delegate forwarder for info.plist key 'AppCenterAppDelegateForwarderEnabled' enabled. It may use swizzling.
default	00:17:47.909308+0200	Recordia	[AppCenter] VERBOSE: +[MSDelegateForwarder flushTraceBuffer]/106 Stop buffering traces, flushed.
default	00:17:47.909858+0200	Recordia	[AppCenter] DEBUG: -[MSSessionContext init]/42 1 session(s) in the history.
default	00:17:47.910725+0200	Recordia	[AppCenter] VERBOSE: -[MSSessionContext setSessionId:]/66 Stored new session with id:(null) and timestamp: 2020-08-27 22:17:47 +0000.
default	00:17:47.910953+0200	Recordia	[AppCenter] DEBUG: -[MSUserIdContext init]/54 1 userId(s) in the history.
default	00:17:47.913481+0200	Recordia	[AppCenter] DEBUG: -[MSDBStorage initWithSchema:version:filename:]_block_invoke/31 SQLite global configuration successfully updated.
default	00:17:47.915502+0200	Recordia	[AppCenter] INFO: -[MSAppCenter configureWithAppSecret:transmissionTargetToken:fromApplication:]/317 App Center SDK configured successfully.
default	00:17:47.915586+0200	Recordia	[AppCenter] VERBOSE: -[MSAppCenter startServices:withAppSecret:transmissionTargetToken:fromApplication:]/343 Start services MSCrashes from an application
default	00:17:47.915802+0200	Recordia	[AppCenterCrashes] DEBUG: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/665 EnableUncaughtExceptionHandler is set to YES
default	00:17:47.915834+0200	Recordia	[AppCenterCrashes] VERBOSE: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/675 Enabled Mach exception handler.
default	00:17:47.920233+0200	Recordia	[AppCenterCrashes] DEBUG: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/707 Exception handler successfully initialized.
default	00:17:47.920315+0200	Recordia	[AppCenterCrashes] DEBUG: +[MSApplicationForwarder registerForwarding]/192 Application forwarder for info.plist key 'AppCenterApplicationForwarderEnabled' enabled. It may use swizzling.
default	00:17:47.920453+0200	Recordia	[AppCenterCrashes] DEBUG: void swizzleReportException()_block_invoke/157 Selector 'reportException:' of class 'NSApplication' is swizzled.
default	00:17:47.920557+0200	Recordia	[AppCenterCrashes] DEBUG: void swizzleSendEvent()_block_invoke/181 Selector 'sendEvent:' of class 'NSApplication' is swizzled.
default	00:17:47.922152+0200	Recordia	[AppCenter] VERBOSE: -[MSSessionContext clearSessionHistoryAndKeepCurrentSession:]/88 Cleared old sessions.
default	00:17:47.922601+0200	Recordia	[AppCenter] VERBOSE: -[MSUserIdContext clearUserIdHistory]/124 Cleared old userIds while keeping current userId.
default	00:17:47.922640+0200	Recordia	[AppCenterCrashes] INFO: -[MSCrashes applyEnabledState:]/412 Crashes service has been enabled.
default	00:17:47.927871+0200	Recordia	[AppCenterCrashes] VERBOSE: -[MSCrashes startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]/457 Started crash service.
default	00:17:47.928494+0200	Recordia	[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/540 Storing a log to Crashes Buffer: (sid: (null), type: startService)
default	00:17:47.928536+0200	Recordia	[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/551 Found an empty buffer position.
default	00:17:47.928733+0200	Recordia	[AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:flags:]_block_invoke/154 Saving log, type: startService, flags: 1.
default	00:17:47.931917+0200	Recordia	[AppCenter] VERBOSE: -[MSLogDBStorage saveLog:withGroupId:flags:]_block_invoke/129 Log is stored with id: '149'
default	00:17:47.932039+0200	Recordia	[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:internalId:]/593 Deleting a log from buffer with id 27897E2E-EAA8-405D-9CA3-888631B09B50
default	00:17:47.988580+0200	Recordia	[AppCenter] INFO: -[MSHttpClient networkStateChanged:]/198 Internet connection is up.
default	00:17:47.988679+0200	Recordia	[AppCenter] INFO: -[MSHttpClient networkStateChanged:]/198 Internet connection is up.
default	00:17:47.988832+0200	Recordia	[AppCenter] INFO: -[MSHttpClient networkStateChanged:]/198 Internet connection is up.
default	00:17:47.988877+0200	Recordia	[AppCenter] INFO: -[MSHttpClient networkStateChanged:]/198 Internet connection is up.
```

**Comment by MatkovIvan** [comment] 2020-08-28 07:33
Whenever you kill a process, there is no crash happening. So, it's expected.

Also, I want to mention that there is no callback or handler to easily detect it. HockeyApp SDK [had](https://github.com/bitstadium/HockeySDK-iOS/blob/011779d37e314479727b8c860eb54527b86fac29/Classes/BITCrashManager.h#L224-L262) **EXPERIMENTAL** heuristic that was based on saving the flag if there was `UIApplicationWillTerminateNotification` event on last session to ensure that it was safely terminated. It was not really reliable, App Center SDK does not support this.

Duplicate of #1848
See original feature request https://github.com/microsoft/appcenter/issues/103

**Closed by MatkovIvan** 2020-08-28 07:33 UTC
Labels: support
