### ISSUE TITLE
XCBBuildService crash of AppCenterCrashes in Xcode16

### ISSUE THREAD

**Issue by eunyongeom** [microsoft/appcenter-sdk-apple#2551] opened 2024-10-22 13:55 UTC
### **Description**

Building AppCenterCrashes in Xcode16 results in a crash as shown below.
```
Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001064a3950

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [61085]
Thread 9 Crashed:
0   XCBCore                       	       0x1064a3950 specialized CommandBuildContext.input.getter + 140
1   XCBCore                       	       0x10627f97c ClangCompilerSpec.constructTasks(_:_:) + 2632
2   XCBTaskConstruction           	       0x105742dbd FilesBasedBuildPhaseTaskProducerBase.constructTasksForRule(_:_:_:) + 1
3   XCBTaskConstruction           	       0x1057ad675 SourcesTaskProducer.constructTasksForRule(_:_:_:_:_:) + 1
4   XCBTaskConstruction           	       0x105745b3d closure #1 in FilesBasedBuildPhaseTaskProducerBase.addTasksForRule<A>(groupContext:_:_:_:_:_:_:) + 1
5   XCBTaskConstruction           	       0x10570717d partial apply for closure #1 in closure #4 in BuildPlan.init(planRequest:taskPlanningDelegate:) + 1
6   XCBTaskConstruction           	       0x1057773c5 closure #1 in SourcesTaskProducer.appendGeneratedTasks(_:options:body:) + 1
7   XCBTaskConstruction           	       0x10570717d partial apply for closure #1 in closure #4 in BuildPlan.init(planRequest:taskPlanningDelegate:) + 1
8   XCBTaskConstruction           	       0x105825505 StandardTaskProducer.appendGeneratedTasks(_:options:body:) + 1
9   XCBTaskConstruction           	       0x105777201 SourcesTaskProducer.appendGeneratedTasks(_:options:body:) + 1
10  XCBTaskConstruction           	       0x10576aa0d specialized FilesBasedBuildPhaseTaskProducerBase.addTasksForRule<A>(groupContext:_:_:_:_:_:_:) + 1
11  XCBTaskConstruction           	       0x10575a5d9 specialized FilesBasedBuildPhaseTaskProducerBase.addTasksForGroup<A>(_:_:_:_:_:_:) + 1
12  XCBTaskConstruction           	       0x105751ec9 specialized 
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Build AppCenterCrashes in Xcode16(16A242d)

### **Details**

1. Which SDK version are you using?
    - 5.0.5
2. Which OS version did you experience the issue on?
    - iOS 18
3. Which Xcode version did you build the app with?
    - Xcode 16 (16A242d)
5. Which Cocoapods version are you using (run `pod --version`)?
    - Carthage 0.39.0
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 16 emulator
7. What language are you using?
    - [ O] Objective C
    - [ O] Swift
8. What third party libraries are you using?
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by nickhingston** [comment] 2024-10-24 14:52
Still an issue with Xcode 16.1 RC

**Comment by MikhailSuendukov** [comment] 2024-11-04 15:36
Hello and thank you for reaching out to us. I am closing this issue as a duplicate of [this one](https://github.com/microsoft/plcrashreporter/issues/317). Please follow the original thread.

**Closed by MikhailSuendukov** 2024-11-04 15:36 UTC
Labels: support

**Comment by DmitriyKirakosyan** [comment] 2024-11-15 08:27
@eunyongeom , @nickhingston , The fix has been merged! Please give it a try and let us know if it resolves the issue for you.

**Comment by nickhingston** [comment] 2024-11-15 16:53
@DmitriyKirakosyan yep archives ok on develop branch

**Comment by bhargavbajani-simformsolutions** [comment] 2024-12-12 11:13
Any plan for when these fixes will be released?

**Comment by MikhailSuendukov** [comment] 2024-12-16 12:49
Hi @bhargavbajani-simformsolutions! Answered in original thread.
