### ISSUE TITLE
Xcode 12.5 Release candidate produces parse issue in AppCenterCrashes

### ISSUE THREAD

**Issue by adincebic** [microsoft/appcenter-sdk-apple#2292] opened 2021-04-21 14:49 UTC
### **Description**

After updating to Xcode 12.5 Release Candidate I am getting build errors for AppCenterCrashes

Parse Issue:
Expected a type, MSChannelDelegate.h
In file included from /Users/adin.cebic/Library/Developer/Xcode/DerivedData/myApp-cjjrwjepgzwfmraokhaqyihrheqt/SourcePackages/checkouts/appcenter-sdk-apple/AppCenterCrashes/AppCenterCrashes/Internals/Model/MSStackFrame.m:4:

### **Repro Steps**

1. Add AppCenter SDK to Xcode project using Swift package manager
2. Try to build or run

### **Details**

1. Which SDK version are you using?
3.3.4
2. Which OS version did you experience the issue on?
macOS 11.2.3
3. Which Xcode version did you build the app with?
Xcode 12.5 Release Candidate
5. Which Cocoapods version are you using (run `pod --version`)?
I am using Swift package manager
6. What device version did you see this error on?  Were you using an emulator or a physical device?
Simulator
7. What language are you using?
    - [ ] Swift
8. What third party libraries are you using?
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
I am unable to build the project, so no logs.

**Comment by DmitriyKirakosyan** [comment] 2021-04-22 15:03
Hi @adincebic 

Thank you for reaching out to us!

Have you tried to integrate AppCenter from `develop`?
Could you please try and let me know if works.

**Comment by DBerto** [comment] 2021-04-27 10:03
Hi @DmitriyKirakosyan I had the same problem and after upgrading to the `develop` version, it started to work! 
Thanks!

**Comment by CristianMoisei** [comment] 2021-04-28 23:34
I ran into the same issue for several apps and the issue is indeed fixed in the `develop` branch.

**Comment by JoeySlomowitz** [comment] 2021-04-30 02:53
Will this be merged onto the master branch soon?

**Comment by DmitriyKirakosyan** [comment] 2021-04-30 10:50
@JoeySlomowitz, There is no specific ETA. I can only say that it is going to happen this quarter.

**Comment by bitops** [comment] 2021-05-04 05:00
@DmitriyKirakosyan I am experiencing this issue on GA XCode 12.5 as well. Are there published instructions for how to point to the develop branch?

And are you really saying that master is broken and you don't know when it will be fixed?

**Comment by sahalin** [comment] 2021-05-09 09:08
Is it safe to use `develop` branch in production?

**Comment by adincebic** [comment] 2021-05-09 11:32
> Is it safe to use `develop` branch in production?

I don't think so. Stuff is getting merged to develop frequently.

**Comment by JagCesar** [comment] 2021-05-10 08:18
@sahalin I'm not sure what the process is to tag a new release, but I guess Microsoft does some kind of QA before a new release. I would assume this isn't done every time something is merged into develop.

**Comment by AnastasiaKubova** [comment] 2021-05-12 07:49
We always perform tests before each merge to the develop, nevertheless we do not recommend use changes from the develop branch in the production. We are planning a release soon and we let you know when it will be ready.

**Comment by sahalin** [comment] 2021-05-14 10:57
@AnastasiaKubova thank you. We have a huge release next week that we've been working on for over a year, and really need analytics and crash reporting. Guess we'll have to take our chances with `develop` and hope that there's 0% chance of crashes on launch 🤞🏻

**Comment by Ahrentlov** [comment] 2021-06-01 09:01
@AnastasiaKubova  Is this fix not hotfix worthy? I mean, it's already in develop and it's tested - would it be a big hassle to  send it out? The AppCenter SDK is right now keeping a plethora of devs around the world from using Xcode 12.5. And quite possibly the upcoming Xcode Beta, from WWDC next week.

I'm sorry, but I'm just baffled by the fact that a huge company like Microsoft, with a solid product like AppCenter, sits on a tested solution, and does nothing. Visual Studio For Mac, Xamarin etc., usually have day 1 fixes for these kind of things.

**Comment by russelarms** [comment] 2021-06-02 09:11
@Ahrentlov sorry for the delay. We are starting the next SDK release, so I hope it will be available in a couple of weeks.

**Comment by AnastasiaKubova** [comment] 2021-06-17 11:31
Hi there! The AppCenter SDK has been [released](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.2.0). Please update to the latest version and let me know if this issue still persists.

**Closed by AnastasiaKubova** 2021-06-17 11:31 UTC
Labels: support
