### ISSUE TITLE
Use of undeclared identifier 'PLCR_FALLTHROUGH'

### ISSUE THREAD

**Issue by chanuuuu** [microsoft/appcenter-sdk-apple#2281] opened 2021-03-23 20:56 UTC
### **Description**
Hi, I am trying to use AppCenter Swift package with analytics and crashes. I am getting use of undeclared identifier 'PLCR_FALLTHROUGH' error when trying to make build with Fastlane, no issue when achieving with xcode though. 

../SourcePackages/checkouts/PLCrashReporter/Source/PLCrashAsyncDwarfExpression.cpp:376:17: [31muse of undeclared identifier 'PLCR_FALLTHROUGH'[0m

                PLCR_FALLTHROUGH;
[36m                ^[0m

[33m▸[0m [39;1mCompiling[0m PLCrashAsyncDwarfEncoding.cpp
[33m▸[0m [39;1mCompiling[0m PLCrashAsyncDwarfCIE.cpp

### **Details**

1. Which SDK version are you using?
    4.1.1
2. Which OS version did you experience the issue on?
    iOS 14
3. Which Cocoapods version are you using (run `pod --version`)?
    Using Swift Package Manager
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. iPhone X physical device, iPhone 8 emulator

**Comment by AnastasiaKubova** [comment] 2021-03-24 13:53
Hi! Thanks for getting in touch with us!
I need some time to check it.

**Comment by DmitriyKirakosyan** [comment] 2021-03-29 06:31
hi @chanuuuu 

I couldn't reproduce the issue. Here is what I tried:

- Created an empty ios project and ran `fastlane init` for it.
- Added AppCenterCrashes and AppCenterAnalytics via SPM, inited AppCenter in AppDelegate
- Built using fastlate's `build_app`
- It worked for me

Could you please provide detailed repro steps for this issue?
Also, what XCode and fastlane versions do you use?

**Comment by AnastasiaKubova** [comment] 2021-04-02 05:53
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Closed by AnastasiaKubova** 2021-04-02 05:53 UTC
Labels: support
