### ISSUE TITLE
Unactionable crash reports

### ISSUE THREAD

**Issue by lwouis** [microsoft/appcenter-sdk-apple#2137] opened 2020-07-30 08:47 UTC
### **Description**

Hi and thanks for the great product!

I'm receiving crash reports which contain pretty much no actionable information, and that seem to me like its AppCenter Crashes SDK itself that's crashing the app.

### **Repro Steps**

This issue is happening to users in the wild, and I have no way to know which steps they took before the crash. I never have random crashes when running the app on my machine.

### **Details**

1. Which SDK version are you using?
    - `pod 'AppCenter/Crashes', '3.3.1'`
2. Which OS version did you experience the issue on?
    - macOS 10.15.4, 10.15.5, 10.15.6, 10.16.0
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.9.1
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - 4 or 5 different models of macbook pro and air
5. What language are you using?
    - Swift
6. What third party libraries are you using?
    - LetsMove, Sparkle, ShortcutRecorder, SwiftyMarkdown, Preferences

### **Integration code**

Here is the [code used to integrate AppCenter Crashes into my macOS app](https://github.com/lwouis/alt-tab-macos/blob/master/src/logic/AppCenterCrashes.swift). It is then [called as the first line in the `applicationDidFinishLaunching` method](https://github.com/lwouis/alt-tab-macos/blob/master/src/ui/App.swift#L38).

### **Crash reports**

![image](https://user-images.githubusercontent.com/106195/88901435-bbb96d00-d28b-11ea-91e6-0abebc97ca98.png)
![image](https://user-images.githubusercontent.com/106195/88901461-c542d500-d28b-11ea-9b51-78fd825bfda9.png)
![image](https://user-images.githubusercontent.com/106195/88901485-cd9b1000-d28b-11ea-89ba-7f59b32c82b7.png)

There are 2 issues at play here.

First one is the lack of actionable information in these 3 reports. It is mentioning `ms_sendEvent
MSApplicationForwarder.m, line 170`, but that code is within the SDK, not within my application code. Am I integrating incorrectly, or is it a limitation of AppCenter Crashes perhaps?

Second is that 2 of the reports mentioned code in `Preferences` so I looked and found a potential issue in that code. I released a new version with a theoretical fix, however, I got the 3rd report, from someone on the version with the fix. On that 3rd report, there is literally nothing I can use to understand what's happening. It looks to me like AppCenter Crashes itself may be crashing the app.

Could you please have a look, and let me know what you think?

Thanks!

**Comment by MatkovIvan** [comment] 2020-07-30 09:01
Hi @lwouis,

Thanks for getting in touch!
It looks like the problem with forwarding events to application class. Hard to say what's wrong without reproduction, but the SDK provides a way to disable this behavior - please find the details in [this article](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/macos#disable-forwarding-of-the-application-main-classs-methods-calls-to-app-center-crashes).

Could you please try to forward it manually as described in that doc and let us know if it helps?

**Comment by lwouis** [comment] 2020-07-30 09:36
Hi @MatkovIvan! Thanks for the quick reply!

I'm a bit unclear on what this swizzling stuff is about. I seem to understand that by default the SDK does some magic to forward 2 methods from `NSApplication`: `reportException` and `sendEvent`. You're asking me to disable that magic, and instead implement them myself, while adding the proper calls to the SDK inside these methods. Am I roughly correct here?

In the instructions you provided, it seems that it's only doable using objc ("Swift's try/catch doesn't work with NSException. These exceptions can be handled in Objective-C only"). My app is 100% Swift, without a line of objc or c. How should I do this then?

Thanks!

**Comment by MatkovIvan** [comment] 2020-07-30 09:47
> You're asking me to disable that magic, and instead implement them myself

Yes, because it looks like the magic doesn't work in your case 😅 We're investigating this but disabling this is the right way to solve it for now.
_Note for future readers: no need to disable it if it just works on your app_

> My app is 100% Swift, without a line of objc or c. How should I do this then?

Yes, this part must be in Objective-C, Swift won't work there. Just add one Objective-C file to the project, Xcode adds it to an app target and resolve the things automatically. No extra actions required.

**Comment by lwouis** [comment] 2020-07-30 09:55
> Just add one Objective-C file to the project, Xcode adds it to an app target and resolve the things automatically. No extra actions required.

Just to be sure I understood correctly, you're saying I can just add a file containing this:

```
@import Cocoa;
@import AppCenterCrashes;

@interface ReportExceptionApplication : NSApplication
@end

@implementation ReportExceptionApplication

- (void)reportException:(NSException *)exception {
  [MSCrashes applicationDidReportException:exception];
  [super reportException:exception];
}

- (void)sendEvent:(NSEvent *)theEvent {
  @try {
    [super sendEvent:theEvent];
  } @catch (NSException *exception) {
    [self reportException:exception];
  }
}

@end
```

And somehow XCode will fill in the gap? Even though I have [my own Swift class inheriting from `NSApplication`](https://github.com/lwouis/alt-tab-macos/blob/master/src/ui/App.swift#L9)? It will make it work, all I have to do is add the file to the project/target?

**Comment by MatkovIvan** [comment] 2020-07-30 10:04
> Even though I have my own Swift class inheriting from NSApplication?

Not in this case, sorry. I guess the simplest way is to inherit your swift class from `ReportExceptionApplication` instead of `NSApplication`. To call objective C from swift you will need [a bridging header](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift).

**Comment by lwouis** [comment] 2020-07-30 10:35
> Update: I see that your class [wasn't really used](https://github.com/lwouis/alt-tab-macos/commit/7037a2d92a6da9f3876ea57d364308b030adcaf4#diff-51570f093954b65f706f7c196303f15bL34), if so simple way should work

Oh! I just finished implementing with bridging headers and `.m` and `.h` files, and having the swift class inherit from the objc class.

You're saying that I can just put the `.m` class as the `NSPrincipalClass`, and keep the swift class inherit from `NSApplication`, and that should work? In that case I'll revert to the simpler usage.

**Comment by MatkovIvan** [comment] 2020-07-30 10:50
As far as I understand, if you want to use inherited from `NSApplication` class you should put it to `NSPrincipalClass` to get it work. But since your class wasn't in plist I'm not sure how it's used in your app, probably I just don't know all application's specifics. My suggestion from that update is based that your class really uses only `NSApplicationDelegate`, but not `NSApplication`, in this case you don't need to keep both `NSApplication` based classes and can put only objective-c one.
So, the question here: is it intended that your class isn't in plist? Are you sure that it's used and you really need inheriting from `NSApplication` there? If so (it's used and required), then bridging is the right way, but if it wasn't used that just changing `NSPrincipalClass` to Objective-C class should work.

**Comment by lwouis** [comment] 2020-07-30 11:02
I don't understand the role of `NSPrincipalClass`. I never touched it in the `Info.plist` thus it used the default `NSApplication`. The [docs](https://developer.apple.com/documentation/bundleresources/information_property_list/nsprincipalclass) are unclear to me on what this key does.

My app inherits from `NSApplication`. It is then instanciated by `App.shared` call in `main.swift`. I think this is pretty standard for a Swift app. I can't remove the inheritance on `NSApplication` as that's needed to make the app run.

I'm unsure of the consequences of having `NSPrincipalClass` be `NSApplication` are. It never seemed to be important as the app runs fine, outputs properly in Console.app for logs and crashes, etc.

I think I will do the heavy solution with bridging header, and all, because I don't understand how just switching the `NSPrincipalClass` to the objc class, and not connecting the objc and swift classes could work.

**Comment by lwouis** [comment] 2020-08-08 16:38
Unfortunately, even after the code changes, I'm still getting these types of crash reports. They mention the objc class now, instead of `MSApplicationForwarder.m`:

![image](https://user-images.githubusercontent.com/106195/89715458-a6a5b200-d9e0-11ea-8a5c-795a67e87844.png)

![image](https://user-images.githubusercontent.com/106195/89715478-c0df9000-d9e0-11ea-9e8a-0311f2384615.png)

These are basically the same thing as it's still crashing on the [sendEvent call](https://github.com/lwouis/alt-tab-macos/blob/master/src/ui/AppCenterApplication.m#L14).

What can I do to improve these reports?

**Comment by MatkovIvan** [comment] 2020-08-10 07:32
Hi @lwouis,

> What can I do to improve these reports?

Aside of symbolycation I don't see what's wrong in these reports. could you please elaborate why do you think that it's SDK (not the Application) issue? [sendEvent](https://developer.apple.com/documentation/appkit/nswindow/1419228-sendevent) is a system method.

**Comment by lwouis** [comment] 2020-08-10 07:41
Other crash reports all point to lines in the application code. Only these sendEvent reports point to code I didn't write. Based on that i thought something was wrong. Especially in the case of the 3rd screenshot in my original message.

Then you told me that you thought it was an issue with the forwarder and i changed the code to do the forwarding manually.

Now you're saying that these crash reports are to be expected? You're right that i'm missing some symbolication from the third-party lib Preferences, but what about the fact that the crash report all point to the sendEvent line instead of a line from the application code like for all other reports?

**Comment by MatkovIvan** [comment] 2020-08-10 08:10
The original message had the reference to the SDK, so the assumption was that something is wrong in our events forwarding code, so I suggested to disable automatic forwarding to exclude potential problem. But now, I don't see that this issue is related to the crash reporter SDK.

> that these crash reports are to be expected?

I'm saying that this looks like correctly reported. It's clear that an app should not crash.

> but what about the fact that the crash report all points to the sendEvent line instead of a line from the application code like for all other reports?

Crashes not always happen in your code; it can be caused by invalid initialization/state so some lib (or even the system one) can crash the app from its code. It's pretty normal (from the crash reporting point of view) that the stack trace doesn't have application code.

**Comment by lwouis** [comment] 2020-08-11 06:54
Ok that make sense!

Now what about this lack of symbolication? When I go in AppCenter, it's showing me:

![image](https://user-images.githubusercontent.com/106195/89763743-170e1980-db2e-11ea-97d7-887d3c354ac2.png)

However, that seems to not be true I think, since some reports have unsymbolicated stack traces, such as:

![image](https://user-images.githubusercontent.com/106195/89763827-3f961380-db2e-11ea-9b51-34e2db740166.png)

I tried to manually upload the symbols, but it's not changing anything. I think this may be due to me using the "Ignore versions" button in the "Unsymbolicated" tab at some point. This UI is quite confusing as there doesn't seem to be a way to review what has been ignored. It may be what's causing me to get partially symbolicated crash reports currently.

How can I fix this situation and get fully symbolicated crash reports?

**Comment by MatkovIvan** [comment] 2020-08-11 07:46
Since it's not SDK issue, I'd suggest you open support ticket on portal instead of the issue here. This way the team will have a chance to check what's going on in your particular case, because they have access to backend/symbolycation process logs. To do it, click the help menu (?) in the upper right corner of the App Center portal, then select **Contact support**. Once you fill out the form, the team will be in contact with you via email.

Closing the issue as it's not SDK related - symbolycation happens on the server side. Thanks for using App Center!

**Closed by MatkovIvan** 2020-08-11 07:46 UTC
Labels: support
