### ISSUE TITLE
Add CocoaPods podspec with XCFramework support for Mac Catalyst

### ISSUE THREAD

**Issue by fabiankr** [microsoft/appcenter-sdk-apple#2113] opened 2020-06-26 14:08 UTC
### **Description**

I want to use the App Center SDK for an universal iOS and macOS Catalyst app. I'm also using CocoaPods.
For backwards compatibility reasons the podspec doesn't support XCFrameworks required for Mac Catalyst.

I understand that this can't be done without causing problems for users that don't want XCFrameworks in their app. Would it be possible to add a separate podspec for the XCFramework support?

### **Repro Steps**

1. Build Mac Catalyst App
2. Integrate AppCenter SDK with CocoaPods

### **Details**

1. Which SDK version are you using?
    - Version 3.3.0
2. Which OS version did you experience the issue on?
    - iOS 13, macOS 10.15
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.9.3
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - real Mac
5. What language are you using?
    - [ x ] Objective C
    - [ ] Swift

**Comment by vvechkanov** [comment] 2020-06-29 11:16
Hi @fabiankr. 

Thank you for creating a separate issue for just creating a CocoaPods podspec with XCFramework support. We will consider this request with a team, but I could not give you any ETA at this moment.

**Comment by imWildCat** [comment] 2020-11-08 13:41
I believe that AppCenter has dropped Xcode 10?

With [this CocoaPods update](https://blog.cocoapods.org/CocoaPods-1.9.0-beta/), we can use xcframework?

**Comment by kumarc-123** [comment] 2020-11-09 05:47
Could you please let us know ETA? Will this issue be resolved?

Four of our iOS projects got affected due to this. The problem is that we do not have sufficient time to migrate to Swift PM and also, not all of our dependencies support Swift PM yet.

**Comment by MatkovIvan** [comment] 2020-11-09 07:19
Hi there,

Yes, Xcode 11 is a minimal supported version and this is possible with CocoaPods update. This thing is also required for properly support `arm64` similators for Apple Silicon. I let you know when I have ETA.

**Comment by Jamminroot** [comment] 2020-11-09 07:20
Hey @imWildCat, yeah, App Center dropped Xcode 10 in the [SDK release 3.3.0](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/3.3.0), so the minimum vesrion is Xcode 11 now.

@kumarc-123 that is going to be addressed, but there's no ETA we can provide yet.

**Comment by imWildCat** [comment] 2020-11-09 07:36
@MatkovIvan 

Thanks! Do you encourage the community to address this issue? Could we contribute PRs for this?

**Comment by Jamminroot** [comment] 2020-11-09 08:33
@imWildCat there's no problem with your opening PR with the change - it should be fairly small. The main thing that would be required is to understand what would be affected by this change (wrapper SDKs is the first thing to come to my mind).

**Comment by ConnorQi** [comment] 2020-12-23 11:25
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.

**Closed by ConnorQi** 2020-12-23 11:25 UTC
Labels: feature request

**Comment by fabiankr** [comment] 2020-12-23 12:39
Works fine, thanks a lot!!
