### ISSUE TITLE
Carthage integration issues with "--no-use-binaries"

### ISSUE THREAD

**Issue by nickfrollo** [microsoft/appcenter-sdk-apple#1794] opened 2019-09-26 00:57 UTC
### **Description**

I am encountering 2 issues with trying to use SDK 2.4.0 under Carthage. 

1. Compile time errors

When compiling with AppCenter from Carthage I get the following compiler error:

`Undefined symbol: ___llvm_profile_runtime`

This is due to the AppCenter SDK being compiled with code coverage flag switched on. Can the project be updated to remove this flag when compiling for Carthage?

I have worked around this issue by enabling "Gather test coverage" on my project schemes but I'd prefer not to have to do this.

Similar examples of this issue:
https://github.com/erikdoe/ocmock/issues/349#issuecomment-366320480
https://github.com/aws-amplify/aws-sdk-ios/issues/833

2. Missing AppCenterDistributeResources.bundle

AppCenterDistribute.framework is missing the resources bundle when compiled with Carthage

![image](https://user-images.githubusercontent.com/47133290/65649910-d7d8f600-e04b-11e9-9081-4b8bfcc4bb32.png)

I can see this bundle exists in AppCenterDistribute.framework if I download a precompiled version of AppCenter SDK so I guess this is missing from the Carthage build process?

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add AppCenter SDK Carthage dependency
2. Update carthage - `carthage update --no-use-binaries --platform iOS`
3. Link AppCenter relevant items:

- AppCenter
- AppCenterAnalytics
- AppCenterCrashes
- AppCenterDistribute

4. Compile

### **Details**

1. Which SDK version are you using?
    - *2.4.0*
2. Which OS version did you experience the issue on?
    - Xcode 10 / iOS 12.4 SDK
3. Which Carthage version are you using?
    - 0.33
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - N/A
5. What language are you using?
    - [ ] Objective C
    - [✅] Swift

**Comment by annakocheshkova** [comment] 2019-09-26 08:00
Hi @nickfrollo! We don't officially support build from sources. Take a look at our [documentation](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios#32-integration-via-carthage) for instructions on Carthage binary integration. 
If you still want to build from sources, for 1st issue you might want to take a look at [this](https://github.com/Carthage/Carthage/issues/2363) and for the second issue, refer to the documentation I sent above (the step about manually linking **Resources** file).

**Comment by nickfrollo** [comment] 2019-09-26 23:40
Compiling from source is pretty crucial for us as vendors don't keep up to date with the latest Swift compiled versions quick enough. I hope this can be fixed as I expect it will affect a large amount of users.

The problem with embedding the resources file is that it doesn't get placed into the Framework when building carthage dependencies so hoping this can also be fixed.

**Comment by annakocheshkova** [comment] 2019-09-27 06:55
Yes, and this is one of the reasons we don't support building from sources for now. The issue is that Carthage doesn't pick up the Resources file in any way and that was a blocker for us.

**Comment by clpolet** [comment] 2019-09-30 15:35
Hi @nickfrollo thanks for reaching out to us. I might misunderstood your use case but since this SDK is written in Objective-C there is no need to recompile from source to be compatible with the different versions of the Swift compiler.

**Comment by nickfrollo** [comment] 2019-09-30 22:47
@clpolet Unfortunately the `--no-use-binaries` is a global flag that must be applied so it doesn't matter if only one particular package has issues, it affects all others regardless of if they are Obj-C or Swift. I've never had this issue with compiling Carthage packages before so I'd suggest it should be fixed to be called Carthage compatible 🙂

**Comment by clpolet** [comment] 2019-10-03 00:48
That's a fair point we'll see what we can do about it.

**Comment by clpolet** [comment] 2019-10-03 01:36
Meanwhile if you don't like enabling "Gather test coverage" but don't mind running an extra Carthage update command you can run `carthage update appcenter-sdk-apple` after your `carthage update --no-use-binaries`.

**Comment by clpolet** [comment] 2019-10-11 22:37
@nickfrollo I came across this in the [Carthage documentation](https://github.com/Carthage/Carthage#swift-binary-framework-download-compatibility):

> Carthage will check to make sure that downloaded Swift (and mixed Objective-C/Swift) frameworks were built with the same version of Swift that is in use locally. If there is a version mismatch, Carthage will proceed to build the framework from source. If the framework cannot be built from source, Carthage will fail.

It looks like you can just use the classic `carthage update` for all your dependencies and if there is a mismatch in the swift version between the binary and your setup it will fallback to building from source. That's nice.

**Comment by nickfrollo** [comment] 2019-10-14 02:26
Unfortunately the way Carthage works in practice is if one binary version is incompatible then it will fallback and build ALL frameworks. So even if AppCenter isn't the framework that's binary incompatible then it will still be rebuilt if another fails.

**Comment by clpolet** [comment] 2019-10-16 17:44
That's too bad, thanks for letting me know.

**Comment by mikecsmith** [comment] 2019-10-23 07:59
Just to add - this is also affecting us - exact same issue as @nickfrollo

**Comment by inPhilly** [comment] 2019-11-07 14:27
Same here.

**Comment by inPhilly** [comment] 2019-11-07 22:05
Two things this is doing with Carthage that no other framework does:
1. Requires "Gather Coverage for <All Targets>" to be checked for Test (Debug)/Options for scheme - to avoid ___llvm_profile_runtime_user error
2. Requires files *NOT* to be included in Run Script/copy frameworks/Input Files - to avoid Archive file validation failing
I am extremely nervous to include this framework in my project.

**Comment by clpolet** [comment] 2019-11-07 23:14
Hi @inPhilly, 
For 1. this only happens if you build from source instead fo integrating the pre-built binaries. Building from source is not supported at the moment because of the issues listed in this thread.
For 2. yes no need to add them to embedded frameworks and no need for a script to strip architectures it's a benefit of static frameworks, they are merged into your application binaries so Xcode does it for you along with your application. No need for these extra steps. It's also documented on the [Carthage repository:](https://github.com/Carthage/Carthage#build-static-frameworks-to-speed-up-your-apps-launch-times) 

> You should not add any of static frameworks as input/output files in carthage copy-frameworks Build Phase.

**Comment by Harrioson** [comment] 2019-11-27 12:06
Microsoft Cloud is an online storage device which the owner is the Microsoft company.
https://www.techsovibe.com/microsoft-cloud/

**Comment by inPhilly** [comment] 2019-11-27 18:20
So basically, if I want to use Carthage without --no-use-binaries, I have to set the "Gather Test Coverage" flag - correct? Could setting this flag possibly affect performance of a live app?

**Comment by JulianAlonso** [comment] 2020-01-21 11:14
Still having `___llvm_profile_runtime_user` when using AppCenter with Carthage `--no-use-binaries` on version `2.5.3`

**Comment by annakocheshkova** [comment] 2020-01-21 12:04
@inPhilly @JulianAlonso Please refer to [this issue in Carthage repo](https://github.com/Carthage/Carthage/issues/2363#issuecomment-453101382).
That's not a bug in App Center Apple SDK.

**Comment by ConnorQi** [comment] 2020-06-23 02:01
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.

**Closed by ConnorQi** 2020-06-23 02:01 UTC
Labels: bug
