### ISSUE TITLE
Details of Swift errors not reported?

### ISSUE THREAD

**Issue by arielelkin** [microsoft/appcenter-sdk-apple#2382] opened 2021-12-15 13:57 UTC
### **Description**

I have a module in my app that can throw the following errors:

```swift
public enum MyError: Error {
    case errorOne
    case errorTwo
    case errorThree
```

Every time an error is thrown, I track it via App Center thus:

```swift
Crashes.trackError(error, properties: properties, attachments: nil)
```

But this results in the following report:

![image](https://user-images.githubusercontent.com/1756909/146199202-764bd755-2d45-40f7-b2cb-8b278b7f2917.png)

There were 95 reports of `MyError` being thrown, but no details on which specific error it was. How can I find those details? 

### **Details**

1. Which SDK version are you using?
    - e.g. 4.3.0
2. Which OS version did you experience the issue on?
    - e.g. macOS 12
3. Which Xcode version did you build the app with?
    - e.g. Xcode 13.1
5. Which Cocoapods version are you using (run `pod --version`)?
    - e.g. 1.10.1
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. MacBook Pro
7. What language are you using?
    - [x] Swift

**Comment by arielelkin** [comment] 2021-12-15 17:25
Hello @DmitriyKirakosyan 

I've tried to crash my app by clicking a button that calls this:

```swift
func buttonClicked()
    func makeCrash() throws {
        throw MyError.errorOne
    }
    try! makeCrash()
}
```

I click the button and it crashes the app as expected. But when I run it again `Crashes.hasCrashedInLastSession` is false, and `Crashes.lastSessionCrashReport` is nil. Could it be because I have the debugger attached? 

How do you suggest I crash the app with these errors?

**Comment by DmitriyKirakosyan** [comment] 2021-12-16 07:57
HI @arielelkin , yes the debugger should not be attached, otherwise the crash reporter will not able to catch the crash.
1. Turn ON verbose logging : `AppCenter.logLevel = .verbose`
2. Disable debugger (`Edit scheme -> Run -> Turn off Debugger`) and run the app
3. Crash the app
4. Enable debugger again and run the app
5. Log with the crash should be displayed in output and sent to the App Center Portal

**Comment by arielelkin** [comment] 2021-12-16 14:48
OK, I followed those steps and got this stack trace, which seems symbolicated:

```
0x00007ff82ce84df4.$sSTsE7forEachyyy7ElementQzKXEKF libswiftCore
0x00007ff81f75cad8._dispatch_call_block_and_release libdispatch
0x00007ff81f75dcc9._dispatch_client_callout libdispatch
NSApplication(NSEvent)._nextEventMatchingEventMask:untilDate:inMode:dequeue: AppKit
NSApplication.run AppKit
```

This crash is reported in the same group as all the others reports of `MyError`, but no details on which specific error it was. 

Also, it's concerning that this last report is shown in App Center as an "Issue" and not a "Crash"!

**Comment by DmitriyKirakosyan** [comment] 2021-12-17 09:39
Hi @arielelkin 

> This crash is reported in the same group as all the others reports of MyError, but no details on which specific error it was.

Yes, swift `Error`'s name is not reported. It is a known issue (https://github.com/microsoft/appcenter-sdk-apple/issues/2367). And it looks like the issue is valid for both errors and crashes..

> Also, it's concerning that this last report is shown in App Center as an "Issue" and not a "Crash"!

I've tested it on iOS and macOS and it worked as expected for me.  Crashes are displayed as "Crash" on the portal. Can you confirm that you crash the app, restart it and the crash report is not appeared on the portal as "Crash"? Note that it may take some time (~5-10min) for it to appear.

**Comment by arielelkin** [comment] 2021-12-20 14:49
OK I can confirm that it does appear on the porta as "Crash".

Do you have an ETA for reporting key information for Swift errors? App Center's error reporting feature won't be helpful for Swift app's otherwise.

**Comment by DmitriyKirakosyan** [comment] 2021-12-21 10:06
Unfortunately, I can't tell any ETA at this moment but this feature is definitely one of the most important on Apple platform, so we will try to take care of it as soon as possible.

I'm closing this issue as a duplicate of #2367.

**Closed by DmitriyKirakosyan** 2021-12-21 10:06 UTC
Labels: support
