### ISSUE TITLE
Cannot add as Swift PM

### ISSUE THREAD

**Issue by guidedways** [microsoft/appcenter-sdk-apple#2263] opened 2021-02-01 00:49 UTC
I get this error when I try and add v4.1.0. No idea what this means and where it's getting 3.3.3 from:

```because root depends on appcenter-sdk-apple 3.3.3..<4.0.0 and root depends on appcenter-sdk-apple 4.1.0, version solving failed.```

**Comment by guidedways** [comment] 2021-02-01 00:52
Why does it say 4.1.0 in `Package.swift` and 4.0.1 in `Package@swift-5.3.swift`?

**Comment by guidedways** [comment] 2021-02-01 01:42
I finally got it to work but now the app fails on a commandline build:

```
While building module 'AppCenterCrashes' imported from /Users/MyUSer/Development/git/MyUSer/calendar/src/Application.m:12:
In file included from <module-includes>:5:
/Users/MyUSer/Library/Developer/Xcode/DerivedData/MyUSer-dfxaoncuargnurehqwjntcnqwbzd/SourcePackages/checkouts/appcenter-sdk-apple/AppCenterCrashes/AppCenterCrashes/include/MSACErrorAttachmentLog.h:16:37: error:
      cannot find interface declaration for 'MSACAbstractLog', superclass of 'MSACErrorAttachmentLog'
@interface MSACErrorAttachmentLog : MSACAbstractLog
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ^
While building module 'AppCenterCrashes' imported from /Users/MyUSer/Development/git/MyUSer/calendar/src/Application.m:12:
In file included from <module-includes>:8:
/Users/MyUSer/Library/Developer/Xcode/DerivedData/MyUSer-dfxaoncuargnurehqwjntcnqwbzd/SourcePackages/checkouts/appcenter-sdk-apple/AppCenterCrashes/AppCenterCrashes/include/MSACCrashes.h:70:26: error:
      cannot find interface declaration for 'MSACServiceAbstract', superclass of 'MSACCrashes'
@interface MSACCrashes : MSACServiceAbstract
~~~~~~~~~~~~~~~~~~~~~~   ^
2 errors generated.
/Users/MyUSer/Development/git/MyUSer/calendar/src/Application.m:12:9: fatal error: could not build module 'AppCenterCrashes'
@import AppCenterCrashes;
```

**Comment by guidedways** [comment] 2021-02-01 01:57
I can confirm that if I switch to the `develop` branch, it builds correctly. So basically v4.1.0 on `master` is broken.

**Comment by MatkovIvan** [comment] 2021-02-01 08:49
Hey @guidedways,
We didn't reproduce this on `master` and I see no changes on `develop` that can affect this. So, I'm assuming that it's some kind of xcode build cache issue.

Closing that because it looks like the problem is solved anyway.

**Closed by MatkovIvan** 2021-02-01 08:49 UTC
Labels: support
