### ISSUE TITLE
Xcode 12.0.1 App run in Release Mode Failure

### ISSUE THREAD

**Issue by Kedar-27** [microsoft/appcenter-sdk-apple#2186] opened 2020-10-08 23:04 UTC
### **Description**
Arm64 failure

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Edit Scheme 
2. In Run Mode , select Release Mode.

### **Details**

1. Which SDK version are you using?
    3.3.4
2. Which OS version did you experience the issue on?
    - e.g. iOS 14
3. Which Cocoapods version are you using (run `pod --version`)?
    - e.g. 1.10.0
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. iPhone X physical device,
     iPhone 8 emulator
5. What language are you using?
    - [ ] Objective C
    - [X] Swift
6. What third party libraries are you using?
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by MatkovIvan** [comment] 2020-10-09 07:29
Hi @Kedar-27,

Thanks for getting in touch! We do not support Apple Silicon yet (arm64 for Simulator). To get successful build please exclude this arch for Simulator from build.

Sorry for the inconvenience.

Duplicate of #2176
Apple Silicon feature request is tracked here - microsoft/appcenter#1927

**Closed by MatkovIvan** 2020-10-09 07:29 UTC
Labels: support
