### ISSUE TITLE
MSErrorReport string representation

### ISSUE THREAD

**Issue by marciniwanicki** [microsoft/appcenter-sdk-apple#1741] opened 2019-08-28 10:10 UTC
### **Description**

`MSErrorReport` is a very clean and nice data class but it's not easily representable by `NSString`. Would be great if there is a method or utils class that helps to convert it to string. 

A member method

```
- (NSString *)description;
```

should be a good candidate, but other options like `- (NSString *)toString;` would also work.

The method could leverage `PLCrashReporter` API:

```
[MSPLCrashReportTextFormatter stringValueForCrashReport:report withTextFormat:PLCrashReportTextFormatiOS];
```

Happy to create a PR if you think this idea is worth pushing forward.

### **Details**

1. Which SDK version are you using? 2.3.0

**Comment by Jamminroot** [comment] 2019-08-28 10:38
Hey, @marciniwanicki, thanks for getting in touch. Ill let our PM team look at your request.

**Comment by hamswan** [comment] 2019-08-30 20:54
Thanks @marciniwanicki we have added this to our feature request

**Comment by hypherion2** [comment] 2019-09-03 20:57
Duplicate of #1720

**Comment by Harrioson** [comment] 2019-11-27 12:09
Microsoft window is an operating system, 
which is needed to be loaded in a computer after purchasing it.
https://www.techsovibe.com/microsoft-windows/

**Comment by AnastasiaKubova** [comment] 2021-04-14 07:30
Yes, this is a duplicate of issue #1720 . Let's track it there.

**Closed by AnastasiaKubova** 2021-04-14 07:30 UTC
Labels: feature request
