### ISSUE TITLE
Missing function to submit custom measurements

### ISSUE THREAD

**Issue by davestjohn** [microsoft/appcenter-sdk-apple#1321] opened 2019-02-21 18:49 UTC
### **Description**

HockeyApp SDK has a function to submit user metrics with custom properties and custom measurements.  The same ability is missing from the AppCenter SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.
2.

### **Details**

1. Which SDK version are you using?
    -1.13.1
2. Which OS version did you experience the issue on?
    - macOS 10.14.3
3. Which Cocoapods version are you using (run `pod --version`)?
    - e.g. 1.4.0
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Mac Pro physical device
5. What language are you using?
    - Objective C
6. What third party libraries are you using?
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by DmitriyKirakosyan** [comment] 2021-12-14 08:34
Hi @davestjohn , I'm closing this issue as a duplicate of https://github.com/microsoft/appcenter/issues/2343. Please follow the progress in the main feature request.

**Closed by DmitriyKirakosyan** 2021-12-14 08:34 UTC
Labels: feature request
