### ISSUE TITLE
Add xcframework in Release binaries

### ISSUE THREAD

**Issue by L1MeN9Yu** [microsoft/appcenter-sdk-apple#2036] opened 2020-04-21 03:18 UTC
**Is your feature request related to a problem? Please describe.**

My app is build for iOS and Maccatalyst, but there is no avalible xcframework found.

**Describe the solution you'd like**

Add the xcframework which can contains all platforms in the release binaries.

**Describe alternatives you've considered**

Add a shell to build the xcframework that contains what the platform you want.

**Additional context**

N/A

**Comment by MatkovIvan** [comment] 2020-04-21 06:51
Duplicate of https://github.com/microsoft/appcenter/issues/1578

**Closed by MatkovIvan** 2020-04-21 06:51 UTC
Labels: feature request
