### ISSUE TITLE
Mac Catalyst Support

### ISSUE THREAD

**Issue by jfahrenkrug** [microsoft/appcenter-sdk-apple#1983] opened 2020-02-18 15:32 UTC
**Is your feature request related to a problem? Please describe.**
I'm using AppCenter in an iPad app that I'd like to bring to macOS using Mac Catalyst. AppCenter is installed via CocoaPods. I have to remove the AppCenter pod when trying to build the app for macOS (using Mac Catalyst). Otherwise I get the following error:

```
ld: in /Users/johannes/Code/testapp/Pods/AppCenter/AppCenter-SDK-Apple/iOS/AppCenter.framework/AppCenter(MSChannelUnitConfiguration.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '/Users/johannes/Code/testapp/Pods/AppCenter/AppCenter-SDK-Apple/iOS/AppCenter.framework/AppCenter' for architecture x86_64
```

**Describe the solution you'd like**
I'd like to be able to compile my app for Mac Catalyst without having to remove the AppCenter pod first. Even if I can't actually *use* all (or any) of AppCenter's functionality on Mac Catalyst, I'd at least like to build the project without having to remove the pod.

**Describe alternatives you've considered**
I'm calling `pod install` with an environment variable when installing the pods for Mac Catalyst. Inside the Podfile I exclude the AppCenter pod when the environment variable is set:

```
if !BUILD_FOR_CATALYST
    pod 'AppCenter', '~> 3.0'
end
```

**Additional context**
N/A

**Comment by MatkovIvan** [comment] 2020-02-18 18:01
Duplicate of https://github.com/microsoft/appcenter/issues/1295

**Comment by MatkovIvan** [comment] 2020-02-18 18:03
Wrong link.

Duplicate of https://github.com/microsoft/appcenter/issues/1578

**Closed by MatkovIvan** 2020-02-18 18:03 UTC
Labels: feature request
