### ISSUE TITLE
In-app updates not working when private track is enabled on iOS

### ISSUE THREAD

**Issue by cabaird** [microsoft/appcenter-sdk-apple#2372] opened 2021-11-22 22:44 UTC
### **Description**

In-app updates are not working when private track is enabled.

### **Repro Steps**

1. Add the App Center Distribute module following the guides here https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios
2. Set the Distribute update track to private
2. Start App Center Distribute

### **Details**

1. Which SDK version are you using?
    - 4.3.0
2. Which OS version did you experience the issue on?
    - iOS 14.8
3. Which Xcode version did you build the app with?
    - Xcode 13.1
5. Which Cocoapods version are you using (run `pod --version`)?
    - N/A (Integration by copying the binaries into your project)
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPad Pro (12.9-inch) (3rd generation)
7. What language are you using?
    - [x] Objective C
    - [ ] Swift
8. What third party libraries are you using?
    - A bunch
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

```
2021-11-22 17:27:11.377364-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] INFO: -[MSACDistribute requestInstallInformationWith:]_block_invoke_5/433 Attempting to use tester app for update setup.
2021-11-22 17:27:11.380718-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] INFO: -[MSACDistribute requestInstallInformationWith:]_block_invoke_5/441 Tester app could not be opened to enable in-app updates (not installed?)
2021-11-22 17:27:11.388384-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] DEBUG: -[MSACDistribute openURLInAuthenticationSessionWith:usePresentationContext:]/728 Using an AuthenticationSession to open URL: https://install.appcenter.ms/apps/**********************************************************************************************************************************************************************************************************************************************************************************************************************ect=true/private-update-setup?release_hash=8f2acd59db1e972af212a7cca785f11c3426593e60f578565e1f48034bc3be27&redirect_id=appcenter-**********************************************************************************************************************************************************************************************************************************************************************************************************************ect=true&request_id=180EAD72-E938-4F22-AD89-95AE04320003&platform=iOS&enable_failure_redirect=true
2021-11-22 17:27:11.420459-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] DEBUG: -[MSACDistribute openURLInAuthenticationSessionWith:usePresentationContext:]_block_invoke/741 Called (null) with error: The operation couldn’t be completed. (com.apple.AuthenticationServices.WebAuthenticationSession error 3.)
2021-11-22 17:27:11.420634-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] ERROR: -[MSACDistribute openURLInAuthenticationSessionWith:usePresentationContext:]/798 Failed to start authentication session.
2021-11-22 17:27:11.434641-0500 HDMS_DRAW[621:87337] IAB.close() called but it was already closed.
```

**Comment by aleksandr-dorofeev** [comment] 2021-11-23 11:09
Hey @cabaird
Thank you for getting in touch with us! 
Logs information that you've shared looks not enough for understanding your issue.
Could you please share more verbose logs?

**Comment by cabaird** [comment] 2021-11-23 14:15
As far as I can tell, I have followed the instructions fully on the guide for setting up Distribute. I want to reiterate that these in-app updates work fine when using the public track. It seems like the issue is with authenticate the user for the private track.

Here is my code for starting Distribute:
```objective-c
[MSACAppCenter configureWithAppSecret:@"<app-secret>"];
[MSACAppCenter setLogLevel:MSACLogLevelVerbose];
[MSACDistribute setUpdateTrack:MSACUpdateTrackPrivate];
[MSACAppCenter startService:[MSACDistribute class]];
```
Here is the entire run log:
```
2021-11-22 17:27:11.264457-0500 HDMS_DRAW[621:87337] Apache Cordova native platform version 5.0.1 is starting.
2021-11-22 17:27:11.264516-0500 HDMS_DRAW[621:87337] Multi-tasking -> Device: YES, App: YES
2021-11-22 17:27:11.273373-0500 HDMS_DRAW[621:87337] [AppCenter] VERBOSE: -[MSACAppCenter startServices:withAppSecret:transmissionTargetToken:fromApplication:]/390 Start services MSACDistribute from an application
2021-11-22 17:27:11.273657-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-22 17:27:11.273679-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-22 17:27:11.273694-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-22 17:27:11.273746-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] INFO: -[MSACDistribute applyEnabledState:]/198 Distribute service has been enabled.
2021-11-22 17:27:11.273768-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] DEBUG: -[MSACDistribute applyEnabledState:]/208 Successfully retrieved distribution group Id setting it in distributeInfoTracker.
2021-11-22 17:27:11.275398-0500 HDMS_DRAW[621:87337] [AppCenter] WARNING: +[MSACKeychainUtil stringForKey:withServiceName:statusCode:]/85 Failed to retrieve item with key='MSUpdateToken', service='com.homedepot.homeservices.dev.hdms.measure.AppCenter' from keychain. OS Status code -25300
2021-11-22 17:27:11.277644-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] INFO: -[MSACDistribute requestInstallInformationWith:]/424 Request information of initial installation.
2021-11-22 17:27:11.277859-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] VERBOSE: -[MSACDistribute startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]/297 Started Distribute service.
2021-11-22 17:27:11.284643-0500 HDMS_DRAW[621:87394] [Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 85 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 85 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}
2021-11-22 17:27:11.285446-0500 HDMS_DRAW[621:87394] [AppCenter] DEBUG: -[MSACChannelUnitDefault enqueueItem:flags:]_block_invoke/155 Saving log, type: startService, flags: 1.
2021-11-22 17:27:11.287199-0500 HDMS_DRAW[621:87394] [AppCenter] VERBOSE: -[MSACLogDBStorage saveLog:withGroupId:flags:]_block_invoke/130 Log is stored with id: '5'
2021-11-22 17:27:11.290358-0500 HDMS_DRAW[621:87337] CDVWKWebViewEngine: trying to inject XHR polyfill
2021-11-22 17:27:11.313261-0500 HDMS_DRAW[621:87337] CDVWKWebViewEngine will reload WKWebView if required on resume
2021-11-22 17:27:11.313301-0500 HDMS_DRAW[621:87337] Using Ionic WKWebView
2021-11-22 17:27:11.313418-0500 HDMS_DRAW[621:87337] [CDVTimer][console] 0.023007ms
2021-11-22 17:27:11.313477-0500 HDMS_DRAW[621:87337] [CDVTimer][handleopenurl] 0.020981ms
2021-11-22 17:27:11.314238-0500 HDMS_DRAW[621:87337] [CDVTimer][intentandnavigationfilter] 0.746012ms
2021-11-22 17:27:11.314286-0500 HDMS_DRAW[621:87337] [CDVTimer][gesturehandler] 0.033021ms
2021-11-22 17:27:11.315009-0500 HDMS_DRAW[621:87337] [CDVTimer][statusbar] 0.694990ms
2021-11-22 17:27:11.318463-0500 HDMS_DRAW[621:87337] [CDVTimer][splashscreen] 3.414989ms
2021-11-22 17:27:11.318602-0500 HDMS_DRAW[621:87337] CDVIonicKeyboard: resize mode 1
2021-11-22 17:27:11.318777-0500 HDMS_DRAW[621:87337] [CDVTimer][cdvionickeyboard] 0.268102ms
2021-11-22 17:27:11.319485-0500 HDMS_DRAW[621:87337] [CDVTimer][file] 0.684977ms
2021-11-22 17:27:11.330826-0500 HDMS_DRAW[621:87337] [CDVTimer][backgroundmode] 11.319995ms
2021-11-22 17:27:11.330873-0500 HDMS_DRAW[621:87337] [CDVTimer][backgroundmode] 0.005960ms
2021-11-22 17:27:11.337681-0500 HDMS_DRAW[621:87337] [CDVTimer][diagnostic] 6.786942ms
2021-11-22 17:27:11.337786-0500 HDMS_DRAW[621:87337] [CDVTimer][socialsharing] 0.069022ms
2021-11-22 17:27:11.337835-0500 HDMS_DRAW[621:87337] [CDVTimer][inappbrowser] 0.033975ms
2021-11-22 17:27:11.337920-0500 HDMS_DRAW[621:87337] [CDVTimer][photolibrary] 0.072956ms
2021-11-22 17:27:11.338033-0500 HDMS_DRAW[621:87337] [CDVTimer][camerapreview] 0.100017ms
2021-11-22 17:27:11.338076-0500 HDMS_DRAW[621:87337] Distribute Started
2021-11-22 17:27:11.338088-0500 HDMS_DRAW[621:87337] [CDVTimer][sharedcordovaappcenter] 0.043035ms
2021-11-22 17:27:11.338097-0500 HDMS_DRAW[621:87337] [CDVTimer][TotalPluginStartup] 24.731040ms
2021-11-22 17:27:11.341015-0500 HDMS_DRAW[621:87337] WF: === Starting WebFilter logging for process HDMS_DRAW
2021-11-22 17:27:11.341055-0500 HDMS_DRAW[621:87337] WF: _WebFilterIsActive returning: NO
2021-11-22 17:27:11.377364-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] INFO: -[MSACDistribute requestInstallInformationWith:]_block_invoke_5/433 Attempting to use tester app for update setup.
2021-11-22 17:27:11.380718-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] INFO: -[MSACDistribute requestInstallInformationWith:]_block_invoke_5/441 Tester app could not be opened to enable in-app updates (not installed?)
2021-11-22 17:27:11.388384-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] DEBUG: -[MSACDistribute openURLInAuthenticationSessionWith:usePresentationContext:]/728 Using an AuthenticationSession to open URL: https://install.appcenter.ms/apps/**********************************************************************************************************************************************************************************************************************************************************************************************************************ect=true/private-update-setup?release_hash=8f2acd59db1e972af212a7cca785f11c3426593e60f578565e1f48034bc3be27&redirect_id=appcenter-**********************************************************************************************************************************************************************************************************************************************************************************************************************ect=true&request_id=180EAD72-E938-4F22-AD89-95AE04320003&platform=iOS&enable_failure_redirect=true
2021-11-22 17:27:11.420459-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] DEBUG: -[MSACDistribute openURLInAuthenticationSessionWith:usePresentationContext:]_block_invoke/741 Called (null) with error: The operation couldn’t be completed. (com.apple.AuthenticationServices.WebAuthenticationSession error 3.)
2021-11-22 17:27:11.420634-0500 HDMS_DRAW[621:87337] [AppCenterDistribute] ERROR: -[MSACDistribute openURLInAuthenticationSessionWith:usePresentationContext:]/798 Failed to start authentication session.
2021-11-22 17:27:11.434641-0500 HDMS_DRAW[621:87337] IAB.close() called but it was already closed.
2021-11-22 17:27:11.849528-0500 HDMS_DRAW[621:87357] Metal API Validation Enabled
2021-11-22 17:27:13.640532-0500 HDMS_DRAW[621:87337] Ionic Native: deviceready event fired after 1984 ms
2021-11-22 17:27:13.656672-0500 HDMS_DRAW[621:87337] OPEN database: hdms_draw_db.db
2021-11-22 17:27:13.670154-0500 HDMS_DRAW[621:87357] Open DB with encryption
2021-11-22 17:27:13.894999-0500 HDMS_DRAW[621:87357] DB open, check sqlite master table OK
2021-11-22 17:27:13.896495-0500 HDMS_DRAW[621:87337] OPEN database: hdms_draw_db.db - OK
2021-11-22 17:27:14.697262-0500 HDMS_DRAW[621:87535] [AppCenter] VERBOSE: -[MSACLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:completionHandler:]/220 Load log(s) with id(s) '5' as batch Id:706A1B55-0237-4646-82C7-932C1FC6BC6F
2021-11-22 17:27:14.701214-0500 HDMS_DRAW[621:87535] [AppCenter] DEBUG: -[MSACChannelUnitDefault sendLogContainer:]/190 Sending 1/1 log, group Id: AppCenter, batch Id: 706A1B55-0237-4646-82C7-932C1FC6BC6F, session Id: (null), payload:
{
  "timestamp" : "2021-11-22T22:27:11.278Z",
  "device" : {
    "screenSize" : "2048x2732",
    "appBuild" : "2.0.0-alpha.8",
    "osName" : "iOS",
    "timeZoneOffset" : -300,
    "carrierCountry" : "us",
    "osVersion" : "14.8",
    "carrierName" : "AT&T",
    "locale" : "en_US",
    "appNamespace" : "com.homedepot.homeservices.dev.hdms.measure",
    "osBuild" : "18H17",
    "sdkName" : "appcenter.ios",
    "oemName" : "Apple",
    "model" : "iPad8,7",
    "sdkVersion" : "4.3.0",
    "appVersion" : "2.0.0-alpha.8"
  },
  "type" : "startService",
  "services" : [
    "Distribute"
  ],
  "distributionGroupId" : "cd6250f9-0ed8-424f-b798-d5919c93cd1a"
}
2021-11-22 17:27:14.702360-0500 HDMS_DRAW[621:87535] [AppCenter] VERBOSE: -[MSACAppCenterIngestion willSendHTTPRequestToURL:withHeaders:]/99 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2021-11-22 17:27:14.702620-0500 HDMS_DRAW[621:87535] [AppCenter] VERBOSE: -[MSACAppCenterIngestion willSendHTTPRequestToURL:withHeaders:]/100 Headers: Content-Type = application/json, App-Secret = ****************************7e2ca23e, Install-ID = BDFEC886-FBB0-4DF2-9F90-F7309CBC0563
2021-11-22 17:27:14.933765-0500 HDMS_DRAW[621:87397] [connection] nw_endpoint_handler_set_adaptive_read_handler [C1.1 40.70.161.7:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed
2021-11-22 17:27:14.934106-0500 HDMS_DRAW[621:87397] [connection] nw_endpoint_handler_set_adaptive_write_handler [C1.1 40.70.161.7:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
2021-11-22 17:27:15.029485-0500 HDMS_DRAW[621:87535] [AppCenter] VERBOSE: -[MSACHttpIngestion printResponse:body:error:]/229 HTTP response received with status code: 200, payload:
{
  "status" : "Success",
  "correlationId" : "f311964b-30f6-4845-beb2-a81ad8c69213",
  "validDiagnosticsIds" : [

  ],
  "throttledDiagnosticsIds" : [

  ]
}
2021-11-22 17:27:15.029780-0500 HDMS_DRAW[621:87535] [AppCenter] DEBUG: -[MSACChannelUnitDefault sendLogContainer:]_block_invoke_3/212 Log(s) sent with success, batch Id:706A1B55-0237-4646-82C7-932C1FC6BC6F.
2021-11-22 17:27:15.037587-0500 HDMS_DRAW[621:87535] [AppCenter] VERBOSE: +[MSACLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/357 Deletion of log(s) by id with value(s) '5' succeeded.
2021-11-22 17:30:30.544173-0500 HDMS_DRAW[621:88319] [AppCenter] VERBOSE: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/479 Identifying object <MSACAppCenter: 0x281fa1f10> added to pause lane for channel AppCenter.
2021-11-22 17:30:30.544341-0500 HDMS_DRAW[621:88319] [AppCenter] DEBUG: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/481 Pause channel AppCenter.
2021-11-22 17:30:30.544642-0500 HDMS_DRAW[621:88319] [AppCenter] VERBOSE: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/479 Identifying object <MSACAppCenter: 0x281fa1f10> added to pause lane for channel AppCenter/one.
2021-11-22 17:30:30.544803-0500 HDMS_DRAW[621:88319] [AppCenter] DEBUG: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/481 Pause channel AppCenter/one.
2021-11-22 17:30:30.544921-0500 HDMS_DRAW[621:88319] [AppCenter] VERBOSE: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/479 Identifying object <MSACAppCenter: 0x281fa1f10> added to pause lane for channel Distribute.
2021-11-22 17:30:30.545050-0500 HDMS_DRAW[621:88319] [AppCenter] DEBUG: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/481 Pause channel Distribute.
2021-11-22 17:30:30.545519-0500 HDMS_DRAW[621:88319] [AppCenter] VERBOSE: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/479 Identifying object <MSACAppCenter: 0x281fa1f10> added to pause lane for channel Distribute/one.
2021-11-22 17:30:30.545630-0500 HDMS_DRAW[621:88319] [AppCenter] DEBUG: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/481 Pause channel Distribute/one.
2021-11-22 17:30:30.545809-0500 HDMS_DRAW[621:88319] [AppCenter] VERBOSE: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/479 Identifying object <MSACAppCenter: 0x281fa1f10> added to pause lane for channel AppCenter/one.
2021-11-22 17:30:30.546075-0500 HDMS_DRAW[621:88319] [AppCenter] VERBOSE: -[MSACChannelUnitDefault pauseWithIdentifyingObjectSync:]/479 Identifying object <MSACAppCenter: 0x281fa1f10> added to pause lane for channel Distribute/one.
2021-11-23 03:41:31.643933-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:41:31.644450-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:41:31.644739-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:41:31.645080-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:41:31.645348-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:41:31.645589-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:41:31.645984-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:41:31.650969-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:41:31.651418-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:38.805280-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:38.805737-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:38.806024-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:38.806453-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:38.806726-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:38.806965-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:38.807348-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:38.811265-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:38.811644-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:44.392167-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:44.392444-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:44.392583-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:44.392702-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:44.392802-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:44.392891-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:44.392997-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:44.396361-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:44.396541-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:45.265690-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:45.266183-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:45.266477-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:45.266771-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:45.267032-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:45.267280-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:45.267704-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:45.270968-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:45.271356-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:56.950520-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:56.951013-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:56.951286-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:56.951582-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:56.951827-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:56.952090-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:56.952477-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:56.959878-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:56.960874-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:57.424376-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:57.424886-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:57.425170-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:57.425601-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:57.425901-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:57.426157-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:57.426550-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:57.430676-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-11-23 03:44:57.431060-0500 HDMS_DRAW[621:87337] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
```

**Comment by cabaird** [comment] 2021-11-24 14:00
I will try to spin up an empty project and see what that brings. This is a Crodpva project. However, I'm modifying the native code directly to add and start this SDK. So for the purposes of this issue, I'm not thinking Cordova should be my issue.

**Comment by cabaird** [comment] 2021-11-25 00:54
Ive solved this. This was a custom Cordova plugin I wrote, which installs the SDKs and follows the guide for starting the services. Unfortunately, at the point of AppDelegate's application(_:didFinishLaunchingWithOptions:) function as it shows in the guide, we run into this issue. So to fix it, I moved that functionality to a separate function so it could be called at a later time, instead of immediately on app launch. This ensures the context is available and in the foreground completely. If anyone else is having this same issue on Cordova, or otherwise, this may be helpful information.

**Comment by DmitriyKirakosyan** [comment] 2021-11-25 08:21
Hi @cabaird, I'm glad the issue is resolved for you.
This looks like a bug, as we always suggest to start SDK in `didFinishLaunchingWithOptions`, but now it doesn't seem to work on iOS 15 when using a private distribution group. I was able to reproduce this bug on a native app.
I created a work item on our board, we will investigate the problem.

May I ask you where do you start AppCenter now? In view controller? Does it work consistently?

**Comment by cabaird** [comment] 2021-11-26 15:58
The way that I'm doing it is working consistently. I'm not sure if you are familiar with how Cordova works, but I added the logic to start AppCenter in a separate function. And then a Javascript function to interface with it from the webview.
 Then, I just call that function when the device is ready using the `deviceready` event in the Javascript (which is pretty standard for Cordova). Here is a guide with more information for that: https://cordova.apache.org/docs/en/5.0.0/cordova/events/events.deviceready.html.

But since I'm controlling when this is being called from the WebView Javascript code, it may not help you in finding exactly where in the iOS code would be safe to trigger the at launch. Maybe there is a way to do a while loop to check that the context is ready before attempting the authentication session?

**Comment by cabaird** [comment] 2021-11-26 16:15
It's worth noting that while it's probably not a great solution overall, a workaround for this can be to delay the execution of the AppCenter start logic.

Ex: Delaying for 1 second:
```objective-c
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 1 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
      [MSACAppCenter configureWithAppSecret:@"<app-secret>"];
      [MSACAppCenter setLogLevel:MSACLogLevelVerbose];
      [MSACDistribute setUpdateTrack:MSACUpdateTrackPrivate];
      [MSACAppCenter startService:[MSACDistribute class]];
  });
```

**Comment by DmitriyKirakosyan** [comment] 2021-11-28 13:47
Thank you @cabaird for these details! Yeah, your approach doesn't help for a native app indeed. I think a similar workaround may work for a react-native app too, so thanks, I'll keep it in mind.

As for delay, right, I would call it a nice solution, so I will try to figure out how to properly wait until the context is ready. We should probably fix it on the SDK level.

**Comment by aleksandr-dorofeev** [comment] 2021-12-15 11:04
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.

**Closed by aleksandr-dorofeev** 2021-12-15 11:04 UTC
Labels: bug
