### ISSUE TITLE
Hang in MSACUility+File.m

### ISSUE THREAD

**Issue by guidedways** [microsoft/appcenter-sdk-apple#2272] opened 2021-02-27 03:07 UTC
I'm on the latest release of AppCenter and it seems at random, our mac app hangs with a `_ulock_wait` on this line (202 in MSACUtility+File.m):

if (!directoryURL || ![directoryURL setResourceValue:@YES forKey:NSURLIsExcludedFromBackupKey error:&error]) {
...

It can at times take several seconds with the app hung on this line. Not sure if there's anything that can be done about this?

**Comment by DmitriyKirakosyan** [comment] 2021-03-01 22:22
Hi @guidedways 

Thank you for getting in touch with us!

Does this happen on a specific macOS version or you experience such issue everywhere?
Could you [turn on verbose logging](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/macos#adjust-the-log-level) and share your logs with us?

Most likely this is an OS issue and there is not much we can really do about it.
However, if you could share more details, we will investigate if this is a bug on the SDK's side.

**Comment by Jamminroot** [comment] 2021-03-12 09:14
It's been a while since we last heard from you, @guidedways. I'm closing the issue for now, but feel free to reopen and verbose logs with us, if the issue is still relevant. Have a great day!

**Closed by Jamminroot** 2021-03-12 09:14 UTC
Labels: support
