### ISSUE TITLE
Warnings when generating DSYM files

### ISSUE THREAD

**Issue by depth42** [microsoft/appcenter-sdk-apple#1862] opened 2019-11-05 08:22 UTC
Hi there,

since upgrading to appcenter 2.3 to 2.5, when compiling our Mac application with Xcode 11.1 or 11.2, we are now seeing these warnings. Does anybody know how to get rid of them?

Cheers

Frank

Showing All Messages
GenerateDSYMFile /Users/frank/Library/Developer/Xcode/DerivedData/Merlin-hafghcjphiuiashgxfmybllhpcws/Build/Products/Debug/MerlinKit.framework.dSYM /Users/frank/Library/Developer/Xcode/DerivedData/Merlin-hafghcjphiuiashgxfmybllhpcws/Build/Products/Debug/MerlinKit.framework/Versions/A/MerlinKit (in target 'MerlinKit' from project 'Merlin')
    cd /Users/frank/Projekte/Merlin4_5/MerlinCode_6.0/Merlin/Merlin
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/frank/Library/Developer/Xcode/DerivedData/Merlin-hafghcjphiuiashgxfmybllhpcws/Build/Products/Debug/MerlinKit.framework/Versions/A/MerlinKit -o /Users/frank/Library/Developer/Xcode/DerivedData/Merlin-hafghcjphiuiashgxfmybllhpcws/Build/Products/Debug/MerlinKit.framework.dSYM

warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/Foundation-3CHX341P345SK.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/Foundation-3CHX341P345SK.pcm
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/Darwin-QU2215416B0G.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/Darwin-QU2215416B0G.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/ObjectiveC-1Y3G4S9BY83MF.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/ObjectiveC-1Y3G4S9BY83MF.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/AppKit-3LDFM4ST6FYYK.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/AppKit-3LDFM4ST6FYYK.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/SystemConfiguration-1XKBGOPI9KIH7.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/SystemConfiguration-1XKBGOPI9KIH7.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/CommonCrypto-379H8CGCYUV50.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/CommonCrypto-379H8CGCYUV50.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/Dispatch-1F1V7L6DRCHIF.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/Dispatch-1F1V7L6DRCHIF.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/CoreServices-R1ROV4XSKFLH.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/CoreServices-R1ROV4XSKFLH.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/CoreGraphics-1ZZ7J4P4C5A8B.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/CoreGraphics-1ZZ7J4P4C5A8B.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/Security-2O4ZGM8V6TNOZ.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/Security-2O4ZGM8V6TNOZ.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/CoreFoundation-2WFA1EITGYJ7J.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/CoreFoundation-2WFA1EITGYJ7J.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/SQLite3-QU2215416B0G.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/SQLite3-QU2215416B0G.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/zlib-QU2215416B0G.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/zlib-QU2215416B0G.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/IOKit-3T18SAMFD10VR.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/IOKit-3T18SAMFD10VR.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/MachO-KTUBWIPJFBHK.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/1WNRIXV89U61O/MachO-KTUBWIPJFBHK.pcm

**Comment by MatkovIvan** [comment] 2019-11-05 09:11
Hi @depth42,

This is a duplicate of #1817 

It's expected to be fixed in the next version. Anyway let's track this problem in the previous issue.

**Comment by inPhilly** [comment] 2019-11-06 02:22
When will this be updated in Carthage?

**Comment by inPhilly** [comment] 2019-11-06 13:46
I just, this morning, updated to the latest version in Carthage. These errors still show. This is *not* fixed.

**Comment by inPhilly** [comment] 2019-11-06 13:48
I am using Carthage/Objective-C.

**Comment by guperrot** [comment] 2019-11-06 19:39
The next version has not been released yet, this was closed as a duplicate so you could track progress in #1817.
Since that closed/duplicate is confusing for you, I am reopening until it's actually released.

**Comment by MatkovIvan** [comment] 2019-11-08 09:09
The SDK 2.5.1 with this fix has been released

**Closed by MatkovIvan** 2019-11-08 09:09 UTC
Labels: known issue
