### ISSUE TITLE
[Question] What is the validity for API tokens generated from AppCenter portal?

### ISSUE THREAD

**Issue by shyamjimishra1993** [microsoft/appcenter-sdk-apple#1833] opened 2019-10-12 07:59 UTC
Hi Team,

We are planning to use the AppCenter CLI command to upload dsym(symbol) file using the following command- 

**appcenter crashes upload-symbols -s path/to/YourApplication.app.DSYM --app "AppCenterOrgId/AppCenterAppId" --token your-appcenter-token**

Once I generate the API Token key from the App center portal and use it with the above command, I am able to upload the dsym file. But after sometime when I try with the same token for uploading, it does not work. Re-creating the API token and using it again works fine.

Just wanted to know the expiry for the API token generated through the AppCenter portal?

Our plan is to add the above command as part of our post-build script on Jenkins. If it was manual, I could have generated a new API key and used it.

Will appreciate any help on this where we don't need to create API tokens multiple times.

Thanks and regards
Shyam Ji Mishra

**Comment by shyamjimishra1993** [comment] 2019-10-14 15:24
Hi Team,

Could you please help us with this query? This will really help us to move forward. Thanks.

**Comment by turanuk** [comment] 2019-10-14 16:45
Hello, yes api-tokens should actually not expire right now - it's possible you are hitting intermittent issues with your old token. Can you please file a support ticket with us so we can look into specifics? https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us

**Comment by turanuk** [comment] 2019-10-14 16:59
Screenshot of the support icon on the bottom right of the screen when you load up appcenter.ms:
![image](https://user-images.githubusercontent.com/723462/66769156-43eb9480-ee69-11e9-985a-3f1df57ddbf5.png)

**Comment by shyamjimishra1993** [comment] 2019-10-15 08:37
Hi @turanuk ,

Thanks for your support here. I have pinged the support team over the app center portal's help page. Waiting on reply. 

So as per you, the token will be valid always and there is no expiry for that.
This means we can hard code the API key(token) into the Jenkins script which will run the cli command to upload the dsym file.

We are using following CLI command to upload dsym symbol-
appcenter crashes upload-symbols -s path/to/YourApplication.app.DSYM --app "AppCenterOrgId/AppCenterAppId" --token your-appcenter-token

**Comment by turanuk** [comment] 2019-10-15 16:21
Yes that is the expected behavior at this time, whether you choose to hardcode or use a variable is mainly up to your individual setup needs.

**Comment by russelarms** [comment] 2019-10-21 07:42
I'm closing this issue now as it seems to be resolved.

**Closed by russelarms** 2019-10-21 07:42 UTC
Labels: question, support
