### ISSUE TITLE
Not able to build iOS project with AppCenter SDK for iPhones on xcode 12.0.1

### ISSUE THREAD

**Issue by mkambale** [microsoft/appcenter-sdk-apple#2300] opened 2021-05-05 11:39 UTC
### **Description**

I updated to latest version in Appcenter pods and from then, not able to build solution for iPhone targets.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Ugrade to Appcenter version 4.1.1
2. Use xcode version 12.0.1 to build the solution
3. Error thrown - 
/Users/----/Library/Developer/Xcode/DerivedData/myctca-cawmjnkvkjcqczeurjzpvzvroxsa/Build/Products/Debug (qa)-iphoneos/AppCenter.framework/AppCenter(MSACAbstractLog.o), building for iOS, but linking in object file built for Mac Catalyst, for architecture arm64

### **Details**

1. Which SDK version are you using?
    - . 4.1.1
2. Which OS version did you experience the issue on?
    - iOS 13+
3. Which Xcode version did you build the app with?
    - e.g. Xcode 12.0.1
5. Which Cocoapods version are you using (run `pod --version`)?
    - e.g. 1.9.3
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - All iPhones
7. What language are you using?
    - [ ] Swift
8. What third party libraries are you using?
 - pod 'AppCenter'
   pod 'Alamofire'
   pod 'AzureCommunicationCalling', '~> 1.0.0-beta.11'
   pod 'AzureCommunication', '~> 1.0.0-beta.11'
   pod 'AzureCore', '~> 1.0.0-beta.11'

**Comment by Jamminroot** [comment] 2021-05-06 06:59
Hey @mkambale, thanks for reaching out.

If I got it right, you are building Catalyst target, which is only supported via SPM or XCF in our SDK, rather than pods.

**Comment by MatkovIvan** [comment] 2021-05-06 07:12
It looks like a duplicate of #2255 and #2251. Please try to update CocoaPods version.

**Comment by AnastasiaKubova** [comment] 2021-05-11 06:07
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Closed by AnastasiaKubova** 2021-05-11 06:07 UTC
Labels: support
