### ISSUE TITLE
App Center Errors for iOS

### ISSUE THREAD

**Issue by joerg04** [microsoft/appcenter-sdk-apple#2022] opened 2020-04-07 12:35 UTC
**Is your feature request related to a problem? Please describe.**
App Center Errors [1] is missing for iOS. I want to track handled exceptions like crashes to get an idea how often they occur and what are the situations causing them.

**Describe the solution you'd like**
The iOS SDK (this project) should get an API for such as in Android SDK eg ```Crashes.trackError(..)```

**Describe alternatives you've considered**
Well, I could use the Analytics API, but we plan to monitor our android errors with scripts, so we have to support multiple APIs for it.

**Additional context**

[1] https://docs.microsoft.com/en-us/appcenter/diagnostics/#errors

**Comment by MatkovIvan** [comment] 2020-04-07 12:58
Duplicate of https://github.com/microsoft/appcenter/issues/192

**Closed by MatkovIvan** 2020-04-07 12:58 UTC
Labels: feature request
