### ISSUE TITLE
Single quotes in document prevent local DB update

### ISSUE THREAD

**Issue by steverhall** [microsoft/appcenter-sdk-apple#1851] opened 2019-10-24 19:49 UTC
### **Description**

Certain characters, like single-quotes, are not valid in SQL insert or update command. These need to be escaped during the write to local DB. 

Have JSON payload similar to:

```
"document": {
        "MessageContent": "It's a new day",
        "UserID": "ChatBot",
        "MessageType": "text",
        ...
    }
```

Receive error:

```
[AppCenter] ERROR: +[MSDBStorage executeNonSelectionQuery:inOpenedDatabase:]/294 Query "REPLACE INTO "appDocuments" ("partition", "document_id", "document", "etag", "expiration_time", "download_time", "operation_time", "pending_operation") 
VALUES ('readonly', 'ChatMessage_efc4b222-d92c-49ee-8b10-02df25bb58fa', '{"UserID":"ChatBot","MessageType":"Text","CategoryID":"10","UserName":"Steve Hall,"Reactions":[],"MessageTime":1571112020,"MessageContent":"It's a new day"}', '"a200edc4-0000-0300-0000-5da544570000"', 1572045098, '1571945098', '1571112023', NULL)" 
failed with error: 1 - near "s": syntax error

```
### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a document payload that has a single-quote in one of the string fields
2. Retrieve record to client app
3. Review Xcode log to see insert/update failure

### **Details**

1. Which SDK version are you using?
    - 2.5
2. Which OS version did you experience the issue on?
    - iOS 13
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.8.4
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 11 Pro Max Simulator
5. What language are you using?
    - [ ] Objective C
    - [X] Swift
6. What third party libraries are you using? None
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by MatkovIvan** [comment] 2019-10-25 12:50
Hi @srhallx,

Thanks for reporting this. I've confirmed the bug.

We'll let you know once it's fixed.

**Comment by Harrioson** [comment] 2019-11-27 11:46
The Microsoft office account is an existing user account on Microsoft account.
https://www.techsovibe.com/microsoft-office-account/

**Comment by russelarms** [comment] 2020-05-11 10:56
I'm closing this issue since the Data module [has been retired](https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) and single quotes work fine for other modules.

**Closed by russelarms** 2020-05-11 10:56 UTC
Labels: bug
