### ISSUE TITLE
App builds using SDK < 4.0.0 crash on launch after run in newer build with 4.0.0 SDK

### ISSUE THREAD

**Issue by mikewoodworth** [microsoft/appcenter-sdk-apple#2259] opened 2021-01-21 19:12 UTC
### **Description**

After updating to version 4.0.0 of the SDK and running our app, all earlier builds crash on launch.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Build app linking to pre 4.0.0 SDK class names and compile
2. Update the app to 4.0.0 SDK and update class names. Compile and run.
3. Launch version built in step 1. <- Crash on launch

### **Details**

1. Which SDK version are you using?
    4.0.0
2. Which OS version did you experience the issue on?
    macOS big sur
5. What language are you using?
    - [x] Objective C
    - [ ] Swift

The issue has to do with the change in class names and how they are being serialized to disk. Older versions open the newer file and crash on NSInvalidUnarchiveOperationException.

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: '*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (MSACSessionHistoryInfo) for key (NS.objects) because no class named "MSACSessionHistoryInfo" was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target). If the class was renamed, use setClassName:forClass: to add a class translation mapping to NSKeyedUnarchiver'
abort() called
terminating with uncaught exception of type NSException

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff2059f083 __exceptionPreprocess + 242
1   libobjc.A.dylib                     0x00007fff202d717c objc_exception_throw + 48
2   Foundation                          0x00007fff212dcc20 ___collectionClasses_block_invoke + 0
3   Foundation                          0x00007fff2127c3e0 -[NSCoder(Exceptions) __failWithExceptionName:errorCode:format:] + 378
4   Foundation                          0x00007fff211974d9 _decodeObjectBinary + 652
5   Foundation                          0x00007fff211997a9 -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:] + 848
6   Foundation                          0x00007fff211b1b0c -[NSArray(NSArray) initWithCoder:] + 161
7   Foundation                          0x00007fff21197d1b _decodeObjectBinary + 2766
8   Foundation                          0x00007fff21197125 _decodeObject + 152
9   Foundation                          0x00007fff21197010 -[NSKeyedUnarchiver decodeObjectForKey:] + 162
10  Foundation                          0x00007fff212546cd +[NSKeyedUnarchiver unarchiveObjectWithData:] + 79
...

**Comment by MatkovIvan** [comment] 2021-01-22 07:30
Hi @mikewoodworth,

Thanks for getting in touch! This case is already discussed in #2212. We cannot change/fix already released versions and do not support [forward compatibility](https://en.wikipedia.org/wiki/Forward_compatibility). However the crashes like that are very unlikely behavior for sure, so we'll avoid such situations in the future.

Closing it as duplicate of #2212

**Closed by MatkovIvan** 2021-01-22 07:30 UTC
Labels: support
