### ISSUE TITLE
AppCenter SDK upgrade errors from 4.0 to 4.2

### ISSUE THREAD

**Issue by CJ99** [microsoft/appcenter-sdk-apple#2329] opened 2021-07-02 18:44 UTC
### **Description**

Received the errors when upgrading the AppCenter SDK from 4.0 to 4.2. Please see the screenshot below.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. CocoaPod install v4.2
2. Build the project in XCode 12.x
3. Receive the errors.

![image](https://user-images.githubusercontent.com/11033446/124316296-a2234400-db32-11eb-9d17-17503ebf5e7f.png)

### **Details**

1. Which SDK version are you using?
    - 4.0
2. Which OS version did you experience the issue on?
    - iOS 14
3. Which Xcode version did you build the app with?
    - Xcode 12.5
5. Which Cocoapods version are you using (run `pod --version`)?
    - 1.8.4
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - none
7. What language are you using?
    - Swift
8. What third party libraries are you using?

**Comment by DmitriyKirakosyan** [comment] 2021-07-04 12:03
Hi @CJ99 

Thank you for reaching out to us.

In short, to make it work you will need to upgrade CocoaPods to version 1.10+.

We are distributing xcframeworks via CocoaPods starting from version 4.1.0 and thus having cocoapods 1.10+ is a requirement now. Please check [CHANGELOG](https://github.com/microsoft/appcenter-sdk-apple/blob/develop/CHANGELOG.md#version-410) or [Apple SDK Prerequisites](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios#1-prerequisites).

**Comment by DmitriyKirakosyan** [comment] 2021-07-04 12:05
I'm closing the issue.
Please let me know if the problem is not resolving after upgrading CocoaPods or you have additional questions.

**Closed by DmitriyKirakosyan** 2021-07-04 12:05 UTC
Labels: support
