### ISSUE TITLE
Do we have any Jenkins plugin/Post Build script  for appcenter to upload dsym symbols?

### ISSUE THREAD

**Issue by shyamjimishra1993** [microsoft/appcenter-sdk-apple#1824] opened 2019-10-09 14:02 UTC
Hi Team,

Thanks a lot for your continuous support!

In our project using the Hockey app, We have Jenkins Post-build script to upload the symbol files for a specified build to HockeyApp.

Do we have any Jenkins Plugin/Post Build script for app center to upload dsym symbol files to App Center?

It would be great if you can point me to some doc which you think will be helpful for this.

Thanks and regards
Shyam Ji Mishra

**Comment by MatkovIvan** [comment] 2019-10-09 15:45
As I can see there is a plugin that actively developed by community: https://github.com/jenkinsci/appcenter-plugin

Duplicate of https://github.com/Microsoft/appcenter/issues/234

As @derpixeldan mentioned there: we won't be adding first party support for Jenkins

**Closed by MatkovIvan** 2019-10-09 15:45 UTC
Labels: not sdk issue, question
