### ISSUE TITLE
Build error in Xcode 15.0 beta

### ISSUE THREAD

**Issue by nicekon** [microsoft/appcenter-sdk-apple#2485] opened 2023-06-08 10:22 UTC
### **Description**

<img width="1501" alt="image" src="https://github.com/microsoft/appcenter-sdk-apple/assets/792574/494b827f-87be-4bf8-822b-735ad3488dbe">
When using the appcenter sdk in Xcode 15.0 beta, the build fails. If you exclude the appcenter sdk, it builds fine.

Error : 
Unable to execute command: Segmentation fault: 11
Linker command failed due to signal (use -v to see invocation)

### **Repro Steps**

Please list the steps used to reproduce your issue.

### **Details**

1. Which SDK version are you using?
    - e.g. 5.0.1
2. Which OS version did you experience the issue on?
    - e.g. iOS 16
3. Which Xcode version did you build the app with?
    - e.g. Xcode 15.0 beta
5. Which Cocoapods version are you using (run `pod --version`)?
    - no
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 13
7. What language are you using?
    - [ ] Objective C
    - [0] Swift
8. What third party libraries are you using?
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by AnatolyPristensky** [comment] 2023-06-08 10:38
Hello @nicekon, and thank for reaching out. 
This is a duplicate of https://github.com/microsoft/appcenter-sdk-apple/issues/2484
Closing as duplicate.

**Closed by AnatolyPristensky** 2023-06-08 10:38 UTC
Labels: support
