### ISSUE TITLE
AppCenter SDK should use UserDefaults instance created with a suite name

### ISSUE THREAD

**Issue by iltercengiz** [microsoft/appcenter-sdk-apple#2342] opened 2021-08-09 21:38 UTC
### **Description**

Using `UserDefaults.standard` internally causes runtime issues while running the app in Debug mode and most probably crashes in the Release builds within apps that have SwiftUI views that utilizes `@AppStorage` property wrapper.

If we were to use SwiftUI's `@AppStorage` property wrapper with `UserDefaults.standard` as the store, internal reads and writes to the same store from the AppCenter SDK are also triggering `AppStorage` property wrapper to run its internal logic. And on top of that, if the reads and writes to `UserDefaults.standard` are from a non-main thread, Xcode shows runtime issues in the debugger. I also have some crashes in App Center Diagnostics dashboard, but this is the furthest I could narrow it down and I don't have any proof that crashes are related, but it seems chances are high.

### **Repro Steps**

1. Integrate the SDK in a project that has a SwiftUI view that uses `@AppStorage` property wrapper. Example:
```swift
struct ContentView: View {
    @AppStorage("some_user_preference") var pref = false
    var body: some View {
        // ... using `pref` here
    }
}
```
2. Run the app and observe runtime issues. Example:
<img width="1440" alt="Screen Shot 2021-08-10 at 12 09 04 AM" src="https://user-images.githubusercontent.com/1618181/128774748-a4da083d-61c0-4f36-bd7f-0f5586200dea.png">

The issue goes away if the app is using a different `UserDefaults` other than `.standard` by providing a suite name within `@AppStorage` property wrapper. Example:
```swift
extension UserDefaults {
    static let local = UserDefaults(suiteName: "UserPreferences")
}
struct ContentView: View {
    @AppStorage("some_user_preference", store: .local) var pref = false
    var body: some View {
        // ... using `pref` here
    }
}
```

Some crashes I've observed on Diagnostics dashboard:
<img width="644" alt="Screen Shot 2021-08-10 at 12 15 58 AM" src="https://user-images.githubusercontent.com/1618181/128775542-0f37bb3a-06f1-46d7-bd15-a92d03c1b206.png">

And it seems these crashes happen right after the app launch.
<img width="514" alt="Screen Shot 2021-08-10 at 12 16 19 AM" src="https://user-images.githubusercontent.com/1618181/128775596-8cb95766-5f5c-41d3-aa14-0ccf0cc5dade.png">

A few disclaimers here:
- Although I noticed the runtime issues while debugging, I neither was able to reproduce the issue nor have a proof that these crashes are related. I just released a new version that uses a custom suite within `@AppStorage` and will observe the crashes from here on.
- All the crashes with the same reason have the Session started -> App crashed events. I don't have any visibility if these were normal user launches or system launching the app in the background.
- I've tried to reproduce the issue in an empty project, but failed to do so. Though, issue is visible and reproducible in my app. Happy to share more info upon request.
- I'm using RevenueCat and the warnings appear wherever it uses `UserDefaults.standard` too. So I'm assuming it's a general issue about utilizing `UserDefaults.standard`.

### **Details**

1. Which SDK version are you using?
    - 4.2.0
2. Which OS version did you experience the issue on?
    - iOS 14 and 15 beta both
3. Which Xcode version did you build the app with?
    - Xcode 12.5 and 13 both
5. Which Cocoapods version are you using (run `pod --version`)?
    - Not related, I used SPM to integrate AppCenter
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Issue is apparent on simulator with Debug builds, also there are crashes on devices
7. What language are you using?
    - [ ] Objective C
    - [x] Swift
8. What third party libraries are you using?
    - RevenueCat, OpenGraph
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
```
2021-08-10 00:22:06.887077+0300 Check Later[5294:58940] [AppCenter] VERBOSE: -[MSACDelegateForwarder addTraceBlock:]_block_invoke_2/88 Start buffering traces.
2021-08-10 00:22:06.887126+0300 Check Later[5294:58940] [AppCenter] DEBUG: -[MSACDelegateForwarder setEnabledFromPlistForKey:]_block_invoke/278 Delegate forwarder for info.plist key 'AppCenterAppDelegateForwarderEnabled' enabled. It may use swizzling.
2021-08-10 00:22:06.887159+0300 Check Later[5294:58940] [AppCenter] VERBOSE: +[MSACDelegateForwarder flushTraceBuffer]/106 Stop buffering traces, flushed.
2021-08-10 00:22:06.887557+0300 Check Later[5294:58940] [AppCenter] DEBUG: -[MSACSessionContext init]/42 1 session(s) in the history.
2021-08-10 00:22:06.888565+0300 Check Later[5294:58940] [AppCenter] VERBOSE: -[MSACSessionContext setSessionId:]/66 Stored new session with id:(null) and timestamp: 2021-08-09 21:22:06 +0000.
2021-08-10 00:22:06.888663+0300 Check Later[5294:58940] [AppCenter] DEBUG: -[MSACUserIdContext init]/54 1 userId(s) in the history.
2021-08-10 00:22:06.899009+0300 Check Later[5294:58940] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-08-10 00:22:06.899363+0300 Check Later[5294:58940] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-08-10 00:22:06.899400+0300 Check Later[5294:58940] [AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
2021-08-10 00:22:06.899470+0300 Check Later[5294:58940] [AppCenter] DEBUG: -[MSACDBStorage initWithSchema:version:filename:]_block_invoke/31 SQLite global configuration successfully updated.
2021-08-10 00:22:06.900802+0300 Check Later[5294:58940] [AppCenter] INFO: -[MSACAppCenter configureWithAppSecret:transmissionTargetToken:fromApplication:]/364 App Center SDK configured successfully.
2021-08-10 00:22:06.904030+0300 Check Later[5294:58940] [AppCenter] VERBOSE: -[MSACAppCenter startServices:withAppSecret:transmissionTargetToken:fromApplication:]/390 Start services MSACCrashes, MSACAnalytics from an application
2021-08-10 00:22:06.923174+0300 Check Later[5294:58940] [AppCenter] VERBOSE: -[MSACSessionContext clearSessionHistoryAndKeepCurrentSession:]/88 Cleared old sessions.
2021-08-10 00:22:06.923435+0300 Check Later[5294:58940] [AppCenter] VERBOSE: -[MSACUserIdContext clearUserIdHistory]/125 Cleared old userIds while keeping current userId.
2021-08-10 00:22:06.926750+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault enqueueItem:flags:]_block_invoke/155 Saving log, type: startService, flags: 1.
2021-08-10 00:22:06.927718+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACLogDBStorage saveLog:withGroupId:flags:]_block_invoke/130 Log is stored with id: '5'
2021-08-10 00:22:06.949172+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel AppCenter.
2021-08-10 00:22:06.949222+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel AppCenter.
2021-08-10 00:22:06.949548+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel AppCenter/one.
2021-08-10 00:22:06.949602+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel AppCenter/one.
2021-08-10 00:22:06.949727+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel Crashes.
2021-08-10 00:22:06.949785+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel Crashes.
2021-08-10 00:22:06.949828+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel Crashes/one.
2021-08-10 00:22:06.949877+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel Crashes/one.
2021-08-10 00:22:06.949963+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel CrashesBuffer.
2021-08-10 00:22:06.950074+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel CrashesBuffer.
2021-08-10 00:22:06.950157+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel CrashesBuffer/one.
2021-08-10 00:22:06.950286+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel CrashesBuffer/one.
2021-08-10 00:22:06.950396+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel Analytics.
2021-08-10 00:22:06.958744+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel Analytics.
2021-08-10 00:22:06.958817+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel Analytics/one.
2021-08-10 00:22:06.958966+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel Analytics/one.
2021-08-10 00:22:06.959086+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel Analytics_critical.
2021-08-10 00:22:06.959122+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel Analytics_critical.
2021-08-10 00:22:06.959200+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel Analytics_critical/one.
2021-08-10 00:22:06.959263+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel Analytics_critical/one.
2021-08-10 00:22:06.959324+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel AppCenter/one.
2021-08-10 00:22:06.959409+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel AppCenter/one.
2021-08-10 00:22:06.959498+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel Crashes/one.
2021-08-10 00:22:06.959533+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel Crashes/one.
2021-08-10 00:22:06.959683+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel CrashesBuffer/one.
2021-08-10 00:22:06.959745+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel CrashesBuffer/one.
2021-08-10 00:22:06.959783+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel Analytics/one.
2021-08-10 00:22:06.959877+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel Analytics/one.
2021-08-10 00:22:06.959943+0300 Check Later[5294:59194] [AppCenter] VERBOSE: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/494 Identifying object <MSACAppCenter: 0x6000038c4d20> removed from pause lane for channel Analytics_critical/one.
2021-08-10 00:22:06.959986+0300 Check Later[5294:59194] [AppCenter] DEBUG: -[MSACChannelUnitDefault resumeWithIdentifyingObjectSync:]/496 Resume channel Analytics_critical/one.
2021-08-10 00:22:10.442794+0300 Check Later[5294:59180] [AppCenter] VERBOSE: -[MSACLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:completionHandler:]/220 Load log(s) with id(s) '5' as batch Id:1CD71530-B323-4A0B-8B3F-2912C07F7046
2021-08-10 00:22:10.443185+0300 Check Later[5294:59180] [AppCenter] DEBUG: -[MSACChannelUnitDefault sendLogContainer:]/190 Sending 1/1 log, group Id: AppCenter, batch Id: 1CD71530-B323-4A0B-8B3F-2912C07F7046, session Id: (null), payload:
2021-08-10 00:22:10.443329+0300 Check Later[5294:59180] [AppCenter] VERBOSE: -[MSACAppCenterIngestion willSendHTTPRequestToURL:withHeaders:]/95 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2021-08-10 00:22:10.443368+0300 Check Later[5294:59180] [AppCenter] VERBOSE: -[MSACAppCenterIngestion willSendHTTPRequestToURL:withHeaders:]/96 Headers: Content-Type = application/json, App-Secret = ****************************8034b3db, Install-ID = 814C4918-0778-484B-BC5A-1357F4319AA0
2021-08-10 00:22:11.313283+0300 Check Later[5294:59184] [AppCenter] VERBOSE: -[MSACHttpIngestion printResponse:body:error:]/229 HTTP response received with status code: 200, payload:
2021-08-10 00:22:11.313357+0300 Check Later[5294:59184] [AppCenter] DEBUG: -[MSACChannelUnitDefault sendLogContainer:]_block_invoke_3/212 Log(s) sent with success, batch Id:1CD71530-B323-4A0B-8B3F-2912C07F7046.
2021-08-10 00:22:11.314648+0300 Check Later[5294:59184] [AppCenter] VERBOSE: +[MSACLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/357 Deletion of log(s) by id with value(s) '5' succeeded.
```

**Comment by AnatolyPristensky** [comment] 2021-08-10 07:14
Hello @iltercengiz , thank you for getting in touch with us!
We will check this issue and reply with results.

**Comment by DmitriyKirakosyan** [comment] 2021-08-12 11:27
Hi @iltercengiz 

We investigated this issue and couldn't reproduce it
I would like to be able to reproduce it locally before fixing it to make sure that it actually fixes the issue.
Regarding best practices of using `UserDefaults`, I can't find any references where it is advised to initialize an instance of `UserDefaults` with `suiteName`, although I notices some SDKs use this technique. Could you please share some links where it is said that `UserDefaults` shouldn't be used as `UserDefaults.standard` and should be instantiated with `suiteName` instead, if you have such?

Also, AFAIK instance created with `suiteName` would write data that can be accessed from other applications, which is not actually intended by the App Center SDK.

> I just released a new version that uses a custom suite within @AppStorage and will observe the crashes from here on.

that would be great, please share new info with us when you get some.

Let's keep this issue open until we get more details on this bug and hopefully can reproduce it.

**Comment by iltercengiz** [comment] 2021-08-25 13:40
Just to share an update, I have released two versions with the `@AppStorage` workaround I mentioned earlier and at the half of all users adoption, I don't see any crashes anymore. Meanwhile, I'll try to reproduce the issue in an example project. 👍🏻

**Comment by DmitriyKirakosyan** [comment] 2021-08-31 22:12
Hi @iltercengiz 

Thank you for the update and your investigation! 👍
Please keep updating us if you have more info. I do want to fix this issue, but we need some repros or proves that using  `UserDefaults.standard` can be an issue with multithreading and Swift UI.

**Comment by DmitriyKirakosyan** [comment] 2021-12-14 09:53
Hi @iltercengiz , I'm going to close this issue as we could not reproduce it. Feel free to reopen it if you have additional information. Contribution PR is always welcome :)

**Closed by DmitriyKirakosyan** 2021-12-14 09:53 UTC
Labels: support

**Comment by iltercengiz** [comment] 2021-12-14 10:05
@DmitriyKirakosyan thank you for your attention as well. I'll share more if I can reproduce or learn more about this too.
