### ISSUE TITLE
Support for user specified application crash handler 

### ISSUE THREAD

**Issue by Lnd-stoL** [microsoft/appcenter-sdk-apple#1982] opened 2020-02-18 14:15 UTC
**Is your feature request related to a problem? Please describe.**
HockeyApp SDK offers BITCrashManagerCallbacks which can be used to specify custom handler for application termination (crash) like this:
```
BITCrashManagerCallbacks callbacks;
callbacks.handleSignal = &some_handler;
[[BITHockeyManager sharedHockeyManager].crashManager setCrashCallbacks:&callbacks];
```
Notice, the handler gets called immediately when the application crashes, not on the next launch when the crash log is being sent to server.
I have not found something similar in the AppCenter SDK.
Such a user specified crash handler is useful for writing some custom crash related info which wont be available upon next app launch (like logs in my case).

**Describe the solution you'd like**
Some way to set custom crash handler in AppCenter SDK.

**Describe alternatives you've considered**
Have not found any alternatives in AppCenter SDK.

**Comment by MatkovIvan** [comment] 2020-02-18 14:45
Hi @Lnd-stoL ,
We already have a feature request for this, closing this as a duplicate.

Duplicate of #1719

**Closed by MatkovIvan** 2020-02-18 14:45 UTC
Labels: feature request
