### ISSUE TITLE
SDK crashes in MSACDBStorage

### ISSUE THREAD

**Issue by manojaher88** [microsoft/appcenter-sdk-apple#2323] opened 2021-06-25 05:48 UTC
### **Description**

The SDK crashes at MSACDBStorage.
I have attached the all the crash files for your reference.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. The app crashes on production application. 
There is no reproducing steps.

### **Details**

1. Which SDK version are you using?
    - 4.1.0
2. Which OS version did you experience the issue on?
    - iOS 12, 13, 14
3. Which Xcode version did you build the app with?
    - Xcode 12.2
5. Which Cocoapods version are you using (run `pod --version`)?
    - 1.10.1
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - physical device - iPhone 11, iPhone 11 Pro, iPhone 11 Pro Max, iPhone XS Max, iPhone 8, iPhone 12 Pro
7. What language are you using?
    - [☑️] Objective C
    - [☑️ ] Swift
8. What third party libraries are you using?
    -   'ActiveLabel', '1.1.0', 'Kingfisher', '5.9.0', 'Charts', '3.6.0', 'EKKeyboardAvoiding', '2.0', 'Leanplum-iOS-SDK', '3.1.2', 'SVProgressHUD', 'SwiftGifOrigin', 'AWSTranscribeStreaming'
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
[report-2517789666130009999-797f2339-f2cc-454a-b4ec-a72feda5d683.txt](https://github.com/microsoft/appcenter-sdk-apple/files/6713800/report-2517789666130009999-797f2339-f2cc-454a-b4ec-a72feda5d683.txt)
[report-2517791328680009999-d62ddfd4-6940-4914-9b1b-0360a18fbb6f.txt](https://github.com/microsoft/appcenter-sdk-apple/files/6713801/report-2517791328680009999-d62ddfd4-6940-4914-9b1b-0360a18fbb6f.txt)
[report-2517785392410009999-815f9845-ee46-4c7d-a461-1671a9e61b37.txt](https://github.com/microsoft/appcenter-sdk-apple/files/6713802/report-2517785392410009999-815f9845-ee46-4c7d-a461-1671a9e61b37.txt)
[report-2517788050830009999-1ea85965-7d8d-4450-acf4-fe5c97177d9f.txt](https://github.com/microsoft/appcenter-sdk-apple/files/6713803/report-2517788050830009999-1ea85965-7d8d-4450-acf4-fe5c97177d9f.txt)
[report-2517785392410009999-815f9845-ee46-4c7d-a461-1671a9e61b37-2.txt](https://github.com/microsoft/appcenter-sdk-apple/files/6713804/report-2517785392410009999-815f9845-ee46-4c7d-a461-1671a9e61b37-2.txt)
[report-2517783733510009999-4255c585-d0e2-401d-a370-6f60caba5d80.txt](https://github.com/microsoft/appcenter-sdk-apple/files/6713805/report-2517783733510009999-4255c585-d0e2-401d-a370-6f60caba5d80.txt)
[report-2517788855270009999-1f4f9e39-6610-465e-ad1e-59e78231d566.txt](https://github.com/microsoft/appcenter-sdk-apple/files/6713806/report-2517788855270009999-1f4f9e39-6610-465e-ad1e-59e78231d566.txt)
[report-2517783065520009999-63827d76-ed7d-44ee-be09-f0688fce6fa8-2.txt](https://github.com/microsoft/appcenter-sdk-apple/files/6713807/report-2517783065520009999-63827d76-ed7d-44ee-be09-f0688fce6fa8-2.txt)
[report-2517783065520009999-63827d76-ed7d-44ee-be09-f0688fce6fa8.txt](https://github.com/microsoft/appcenter-sdk-apple/files/6713808/report-2517783065520009999-63827d76-ed7d-44ee-be09-f0688fce6fa8.txt)
[report-2517784218220009999-0e7e9a2e-3170-4898-bb8d-ececfb9e8b9e.txt](https://github.com/microsoft/appcenter-sdk-apple/files/6713809/report-2517784218220009999-0e7e9a2e-3170-4898-bb8d-ececfb9e8b9e.txt)
[report-2517792023950009999-4445da00-c12c-4e94-b1b6-4a6253baa3f3.txt](https://github.com/microsoft/appcenter-sdk-apple/files/6713810/report-2517792023950009999-4445da00-c12c-4e94-b1b6-4a6253baa3f3.txt)
[report-2517779878360009999-1e68f983-8498-4993-be28-0e3cc3efd9a7.txt](https://github.com/microsoft/appcenter-sdk-apple/files/6713811/report-2517779878360009999-1e68f983-8498-4993-be28-0e3cc3efd9a7.txt)

**Comment by AnastasiaKubova** [comment] 2021-06-28 06:56
Hi! Thanks for getting in touch with us! 
Could you please clarify did this issue happen on the previous App Center versions also or this issue happens only in the `4.1.0` version?

**Comment by manojaher88** [comment] 2021-06-29 04:30
Hi @AnastasiaKubova, 
We have not used the previous version of App-Center SDK. 
We started with **4.1.0**

**Comment by AnastasiaKubova** [comment] 2021-06-29 05:48
Could you please share a code snippet where and how you use App Center SDK?

**Comment by manojaher88** [comment] 2021-06-29 06:47
This is the only code that we are using
`// Called from didFinishLaunchingWithOptions
-(void)initializeAppCenter {
    NSString *appcenterKey = [AppCenterHelper getAppcenterKey];
    if (appcenterKey != nil)
        MSACCrashes.delegate = self;
        [MSACAppCenter start:appcenterKey withServices:@[[MSACAnalytics class], [MSACCrashes class]]];
    if ([MSACCrashes hasCrashedInLastSession]) {
        MSACErrorReport *report = [MSACCrashes lastSessionCrashReport];
        NSDate *errorDate = [report appErrorTime];
        if (errorDate == nil) {
            errorDate = [NSDate date];
        }
        NSString *crashDate = [errorDate getStringFromDate];
        NSLog(@"The crash date is %@", crashDate);
    }
}


// In swift file. Called after login.
Analytics.trackEvent("Crash user name", withProperties: ["userName" : name])`

**Comment by AnastasiaKubova** [comment] 2021-06-29 07:58
Does this issue happen in the first seconds after the start application or it happens at any time? Do you use the `sqlite3` library in your project?

**Comment by manojaher88** [comment] 2021-06-29 08:02
This crash occurs once in 3K logins.
We do not use sqlite, but we do use Core-Date.

**Comment by DmitriyKirakosyan** [comment] 2021-07-04 16:15
Hi @manojaher88 

I checked your logs and it seems that this issue is happening because the library [Leanplum](https://github.com/Leanplum/Leanplum-iOS-SDK) (that you use in your project) is conflicting with AppCenter SDK while opening an sqlite connection.
The issue is fixed in the latest release of `Leanplum-iOS-SDK` (3.2.0), see: https://github.com/Leanplum/Leanplum-iOS-SDK/pull/436.

Please update the `Leanplum-iOS-SDK` to version `3.2.0`. This should fix the bug.
I'm closing this issue but feel free to reopen it if this suggestion doesn't help.

**Closed by DmitriyKirakosyan** 2021-07-04 16:15 UTC
Labels: bug
