### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by phiren** [microsoft/appcenter-sdk-apple#2111] opened 2020-06-25 07:19 UTC
### **Description**

Not able to build using apple Xcode 12 Universal beta for Apple Silicon

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Integrate SDK for Mac app
2. Use Xcode 12 Universal beta, building it gives error as below:
ld: warning: ignoring file /Volumes/Projects/Hiren/Projects-Live/Mac/Project/2. sourcecode/Pods/AppCenter/AppCenter-SDK-Apple/macOS/AppCenter.framework/AppCenter, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file /Volumes/Projects/Hiren/Projects-Live/Mac/Project/2. sourcecode/Pods/AppCenter/AppCenter-SDK-Apple/macOS/AppCenterAnalytics.framework/AppCenterAnalytics, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file /Volumes/Projects/Hiren/Projects-Live/Mac/Project/2. sourcecode/Pods/AppCenter/AppCenter-SDK-Apple/macOS/AppCenterCrashes.framework/AppCenterCrashes, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MSAnalytics", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_MSAppCenter", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_MSCrashes", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### **Details**

1. Which SDK version are you using?
Appcenter sdk 3.3.0
2. Which OS version did you experience the issue on?
Mac OS Big sur, 11.0 beta
3. Which Cocoapods version are you using (run `pod --version`)?
pod version 1.9.3
4. What device version did you see this error on?  Were you using an emulator or a physical device?
On Mac, MacOS Big sur 11.0
5. What language are you using?
    - [ ] Objective C
    - [ ] Swift
6. What third party libraries are you using?
Only one, AppCenter SDK
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
It fails during compilation time, so no logs

**Comment by MatkovIvan** [comment] 2020-06-25 07:45
Hi @phiren,

Thanks for getting in touch! It's kind of expected now. In addition, you are trying to use CocoaPods for that, although it supports distributing `.xcframework`, it requires some breaking changes for existing customers, so we're distributing `.xcframework` only as GitHub asset.
Anyway, I'm marking it as a feature request. No ETA at the moment.

**Comment by fabiankr** [comment] 2020-06-26 14:10
> Hi @phiren,
> 
> Thanks for getting in touch! It's kind of expected now. In addition, you are trying to use CocoaPods for that, although it supports distributing `.xcframework`, it requires some breaking changes for existing customers, so we're distributing `.xcframework` only as GitHub asset.
> Anyway, I'm marking it as a feature request. No ETA at the moment.

Would it be possible to add a separate podspec for `.xcframework` support? I need this for Mac Catalyst (support officially added in v3.3.0 which is awesome) and it's kind of annoying that it only works with the downloaded files and not CocoaPods... See https://github.com/microsoft/appcenter-sdk-apple/issues/2113

**Comment by vvechkanov** [comment] 2020-06-29 11:18
Hi @phiren.

As I answered in #2113, we discuss the possibility to add additional podspec with a team, but I could not give you any ETA at this moment.

**Comment by duncanwilcox** [comment] 2020-08-12 12:37
Apple Silicon is getting closer, and we'd like to build our app with all dependencies, including AppCenter. Any ETA at this time?

**Comment by iamclement** [comment] 2020-08-19 18:10
Thanks for reaching out. Let's move this conversation to the App Center main repository for visibility. There's an existing [issue](/microsoft/appcenter/issues/1927) on this topic there.

**Comment by iamclement** [comment] 2020-08-20 16:59
Closing this issue as a duplicate of this other [issue](/microsoft/appcenter/issues/1927).

**Closed by iamclement** 2020-08-20 16:59 UTC
Labels: feature request

**Comment by yesthisisjoe** [comment] 2020-09-12 19:37
> Thanks for getting in touch! It's kind of expected now. In addition, you are trying to use CocoaPods for that, although it supports distributing `.xcframework`, it requires some breaking changes for existing customers, so we're distributing `.xcframework` only as GitHub asset.
Hi @MatkovIvan, I searched this repo but I can't find the .xcframework file(s). Can you point me towards them? Thanks!

**Comment by AnastasiaKubova** [comment] 2020-09-14 05:28
Hello, @yesthisisjoe ! Thanks for getting in touch with us!
You can find `. xcframework` files on the [releases page ](https://github.com/microsoft/appcenter-sdk-apple/releases).

Thanks
