### ISSUE TITLE
Crash -[MSACHttpClient requestCompletedWithHttpCall:data:response:error:]

### ISSUE THREAD

**Issue by iCodeWoods** [microsoft/appcenter-sdk-apple#2467] opened 2023-02-13 06:53 UTC
### **Description**

SDK crashed in -[MSACHttpClient requestCompletedWithHttpCall:data:response:error:].

<img width="875" alt="image" src="https://user-images.githubusercontent.com/30431268/218390446-c202cdc9-b1dc-408e-8b23-3c93243c82aa.png">

Here are some crash reports:
[report-2517260424140009999-4dfa1496-2a27-4476-88d5-21ab56d53ad7.txt](https://github.com/microsoft/appcenter-sdk-apple/files/10719442/report-2517260424140009999-4dfa1496-2a27-4476-88d5-21ab56d53ad7.txt)
[report-2517263047240009999-e6511589-0c89-4605-a661-fa9537ccb3c3.txt](https://github.com/microsoft/appcenter-sdk-apple/files/10719443/report-2517263047240009999-e6511589-0c89-4605-a661-fa9537ccb3c3.txt)
[report-2517263043410009999-fb6f2cd6-cb33-481b-836c-2380d6ff0e72.txt](https://github.com/microsoft/appcenter-sdk-apple/files/10719444/report-2517263043410009999-fb6f2cd6-cb33-481b-836c-2380d6ff0e72.txt)
[report-2517263042740009999-136bdfc2-2351-4ca7-951d-0fa3cb99738d.txt](https://github.com/microsoft/appcenter-sdk-apple/files/10719445/report-2517263042740009999-136bdfc2-2351-4ca7-951d-0fa3cb99738d.txt)

### **Repro Steps**

Online issue. Can't repro.

### **Details**

1. Which SDK version are you using?
    - 5.0.0
2. Which OS version did you experience the issue on?
    - Online monitor, all iOS version
3. Which Xcode version did you build the app with?
    - Xcode 14.2
5. Which Cocoapods version are you using (run `pod --version`)?
    - 1.10.1
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Online monitor, all kinds of physical device
7. What language are you using?
    - [x] Objective C
    - [x] Swift

**Comment by IlyaBausovAkvelon** [comment] 2023-02-13 23:42
@iCodeWoods Thank you for your report. We will need some time to take a look.

**Comment by DmitriyKirakosyan** [comment] 2023-02-16 07:43
Hello @iCodeWoods , I believe [this change](https://github.com/microsoft/appcenter-sdk-apple/pull/2461) can potentially fix this bug.
We are planning to release apple sdk this month, and you will be able to test if the problem is gone.

**Comment by iCodeWoods** [comment] 2023-02-17 03:36
> Hello @iCodeWoods , I believe [this change](https://github.com/microsoft/appcenter-sdk-apple/pull/2461) can potentially fix this bug. We are planning to release apple sdk this month, and you will be able to test if the problem is gone.

Awesome! Thanks.

**Comment by iCodeWoods** [comment] 2023-02-24 11:29
Hi @DmitriyKirakosyan , is there any updates about 'release apple sdk this month'?

**Comment by iCodeWoods** [comment] 2023-03-07 02:39
Hi @DmitriyKirakosyan , Any updates?

**Comment by DmitriyKirakosyan** [comment] 2023-03-08 10:34
Hi @iCodeWoods , we are working on the release right now. Expected to be this week. The last changes I would like to get included in the release is https://github.com/microsoft/appcenter-sdk-apple/pull/2470, so we get it merged first and then start the release. Thanks for patience.

**Comment by AnatolyPristensky** [comment] 2023-03-10 14:55
Hello @iCodeWoods, the new [5.0.2](https://github.com/microsoft/appcenter-sdk-apple/releases) version is released, so I'm closing this issue. 
Please, feel free to reopen it if you still facing the issues.

**Closed by AnatolyPristensky** 2023-03-10 14:55 UTC
Labels: support
