### ISSUE TITLE
Unarchiving data crash due to the prefix change for some classes

### ISSUE THREAD

**Issue by benoitsan** [microsoft/appcenter-sdk-apple#2212] opened 2020-11-06 13:56 UTC
### **Description**

I found a crash using the sdk built from sources using this commit https://github.com/microsoft/appcenter-sdk-apple/commit/060b043fe4b8653541427dec376172440f435247.

Previous versions of my application linking an older version of AppCenter SDK are crashing at launch. 

The crash is:

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: '*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (MSACSessionHistoryInfo) for key (NS.objects) because no class named "MSACSessionHistoryInfo" was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target). If the class was renamed, use setClassName:forClass: to add a class translation mapping to NSKeyedUnarchiver'
abort() called
terminating with uncaught exception of type NSException
```

I think it's because prefix in class names change from MS to MSAC in the newest SDK. The SDK is probably encoding some classes in the UserDefaults. As a consequence, older versions of the application using an older SDK crash because they try to unarchive the same UserDefaults containing unknown classes names.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Link an application using an older version of the SDK before the class names change (in my case: it's version 3.3.4)
2. Launch the application.
3. Link the same application to the SDK after the class names change
4. Launch the application. It should crash at launch.

### **Details**

1. Which SDK version are you using?
    - https://github.com/microsoft/appcenter-sdk-apple/commit/060b043fe4b8653541427dec376172440f435247
2. Which OS version did you experience the issue on?
    - macOS 10.15.7
3. Which Cocoapods version are you using (run `pod --version`)?
    - unknown
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - MacBook Pro (15-inch, 2018)
5. What language are you using?
    - [x] Objective C
    - [x] Swift
6. What third party libraries are you using?
    n/a
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
    n/a (app is crashing at launch)

**Comment by DmitriyKirakosyan** [comment] 2020-11-06 14:25
@benoitsan Thanks for getting in touch!

I'll look into it and get back to you shortly.

**Comment by DmitriyKirakosyan** [comment] 2020-11-06 22:42
@benoitsan, sorry for the delay

I've reproduced the error, but the repro steps are different from yours. It's actually failing with this error when you downgrade the lib from version with `MSAC` prefix to version with `MS` prefix (from newer to older). So the repro steps are the following:

1. Link an application to the SDK after the class names change
2. Launch the application.
3. Link the same application using an older version of the SDK before the class names change
4. Launch the application. It should crash at launch.

Note that I just reversed your steps 1. and 3.

This scenario is expected, because downgrading SDK is not supported. If you integrated a newer version of the lib with a breaking change like this prefix change, then downgrading it for the same app could lead to an unpredicted behaviour, due to the difference in UserDefaults usage.

On the other hand, upgrading the SDK to a newer version within the same app shouldn't produce any errors.

Please let me know if my explanation makes sense to you.

**Comment by benoitsan** [comment] 2020-11-09 08:28
@DmitriyKirakosyan I'm sorrry, as you noticed correctly, I made a mistake in the repro steps.

On the other hand, I don't agree that downgrading AppCenter SDK should not be supported. Backward compatibility is primordial for a macOS application in my opinion. I will give you some examples motivating this statement:
- If you a have a bug in your latest version, the user can still use the previous version.
- As a developer, you need to be able to launch your previous versions. As long as they are minor versions, backward compatibility should not be an issue.

Finally and more important, a crash/analytics framework is not a component of your application that should break the backward compatibility of your application.

**Comment by Jamminroot** [comment] 2020-11-09 08:45
As you pointed out, minor version changes should not break backwards compatibility, but the changes in prefixes are not yet released, and going to be released as a part of next major release which would also include other changes.
Currently they are only available in development branch.

**Comment by benoitsan** [comment] 2020-11-09 08:52
@Jamminroot I filed this bug report in the context of the next major release, to warn you about this bug, I didn't expect a fix in the development branch. So, if you plan to fix it for the release, it's perfect. Thank you.

**Comment by Jamminroot** [comment] 2020-11-09 09:32
Oh, sorry for misunderstanding then :slightly_smiling_face: 

Also, you might've meant forward compatibility of the SDK? Since downgrading from newer SDK version (with the new format of data), to the older version (with the older format of data), so that the older version of the SDK would work fine with the newer data format, would mean forward compatibility (compatibility with planned data format, from the older release point-of-view), opposite to backward compatibility, where newer version of SDK would support the older data format. 

If so - that would require fixing older, already existing release, and we don't have any plans in this regards.

**Comment by benoitsan** [comment] 2020-11-09 09:41
Sorry for my mistake, once again. You are right, I meant forward compatibility.

**Comment by Jamminroot** [comment] 2020-11-09 10:51
I see. Well, the scenario with SDK downgrade to version prior to the next release is not going to work with the next release.

**Comment by Jamminroot** [comment] 2020-11-09 12:34
I'm closing the ticket now, but feel free to reopen whether you feel like it.

**Closed by Jamminroot** 2020-11-09 12:34 UTC
Labels: support

**Comment by rsebbe** [comment] 2020-11-19 11:41
Just wanted to point out this is an important regression that will affect AppCenter SDK users out there.

- App 1.0 uses a previous AppCenter SDK
- App 1.1 uses e newer AppCenter SDK
- if an app user downloads and runs App 1.1, all successive launches of App 1.0 will lead to a crash at launch. 

Fixing that on the user side is pretty involved (erasing keys in the defaults database). Moreover, redownloading an older version of an app is a pretty common scenario, and I think this should be possible & not prevented by a dependency of the app.

I'd suggest either of these approaches to solve this:
- use distinct keys to store SDK data as the serialized format has changed and is incompatible with the previous one. Possibly with only upward data migration.
- use a more robust approach to serialization (archiving is fragile, a dictionary/json/plist might help together with necessary data validation) if you intend to share data across versions. With a focus on preventing crashes.

Thanks!

**Comment by MatkovIvan** [comment] 2020-11-20 09:35
Hi @rsebbe, thanks for reaching out and for your suggestions. However, this specific crash is handled in the last version of SDK, so regression is the not right term of it. I understand that the crash is very unlikely behavior,  but as @Jamminroot mentioned above, we do support backward compatibility but not forward compatibility. 
Also, Apple doesn't allow downloading old versions of the apps from store (or I'm missing something?)

I'll discuss with the team how/if we can mitigate this.

**Comment by rsebbe** [comment] 2020-11-20 10:13
Thank you, appreciated. 

Mac apps can be distributed outside of the App Store, and older versions can be re-downloaded, restored from backups, etc. Also, not requesting full forward compatibility but forward "crash-proofing" for a known breaking change, as, I think we can agree here, crash is not a great experience for users & we developers (SDK users) have no control on that unless we modify the AppCenter SDK.

Alternatively, if you don't want to handle that in the framework, you could at least expose the root defaults key in the API, so that we (developers) can bypass the problem by saving new data elsewhere. (it's something we're currently investigating internally as a fork)
