### ISSUE TITLE
Creating a Crash log file in App Support bundle as well once a crash is reported

### ISSUE THREAD

**Issue by shyamjimishra1993** [microsoft/appcenter-sdk-apple#1617] opened 2019-05-14 14:52 UTC
Hi, 

Thanks for your support on my last issue. 

We have a requirement, where we want to create a crash log report in App Support Bundle as well along with uploading it to App Center. So that when the customer reports a bug and shares the logs with us, We will have Crash logs report there as well.

Using PLCrashReporter, This is how we can achieve it.

PLCrashReporter * crashReporter = [[PLCrashReporter alloc] initWithConfiguration:[PLCrashReporterConfig defaultConfiguration]];
NSData * crashData = [crashReporter loadPendingCrashReportDataAndReturnError:&error];
PLCrashReport *plCrashReport = [[PLCrashReport alloc] initWithData:crashData error:&error];
NSString *report = [PLCrashReportTextFormatter stringValueForCrashReport:plCrashReport
                                                                          withTextFormat:PLCrashReportTextFormatiOS];
 BOOL flag = [report writeToFile:@"appDirectoryPathGoesHere.crash"
                             atomically:YES
                               encoding:NSUTF8StringEncoding
                                  error:&err];

This will create a .crash file in App support bundle at a specified path location.

Is there a way to achieve something similar using AppCenter SDK. 

Problem Statement:-
Along with uploading crashes to AppCenter, We also want to have few(ex. 10 last crashes) to be stored into app support bundle. So that we could get them when the user reports an issue and shares the logs.

Any lead on this would be really appreciated. Looking forward to hearing back!!

Thanks and regards
Shyam Ji Mishra

**Comment by clpolet** [comment] 2019-05-14 20:45
Hi @shyamjimishra1993, thanks for contacting us. I am trying to get this right. Let me know if I understood correctly. You'd like to save AppCenter crashes reports into some place (inside the [Application Support](https://developer.apple.com/documentation/foundation/nssearchpathdirectory/nsapplicationsupportdirectory?language=objc) directory) so that when a customer is reporting a bug to you they can bundle the crashes and attach them to the bug report. Is that right?

Couple of questions: 

- Which platform is you application for?

- You said customers are reporting bugs to you, what's the process, where are they reporting the bugs?

**Comment by clpolet** [comment] 2019-05-14 21:21
What I described is possible today because you can have your hands on each crash report before it's sent to AppCenter. Simply set a delegate on MSCrashes as described in [the crashes documentation](https://docs.microsoft.com/appcenter/sdk/crashes/ios#the-following-callback-will-be-invoked-before-the-sdk-sends-a-crash-log) and implement the `crashes:willSendErrorReport:` delegate method. This method is invoked before the SDK sends a crash log. It gives you access to the `errorReport` object.

**Comment by shyamjimishra1993** [comment] 2019-05-15 03:32
Hi, 

Thanks for your support on this. Please find below the answers for your questions.

**Which platform is you application for?**
Ans: iOS

**You said customers are reporting bugs to you, what's the process, where are they reporting the bugs?**
We have an option in our app where customers can click and they can report an issue via mail to us. This mail will contain the Logs which we write to a CSV file, Issue description text entered by the user, Some other metadata related to app, And The stored Crash logs written to app directory Using PLCrashReporter as mentioned above in the issue description.

Will investigate further on crashes:willSendErrorReport: and get back to you in case of any doubt.

I want the crash report(filename.crash) file in my App directory as you can see in the below attached image. Let me know how we can achieve it from MSErrorReport object received through crashes:willSendErrorReport delegate.

<img width="1214" alt="Screenshot 2019-05-15 at 8 58 07 AM" src="https://user-images.githubusercontent.com/20599875/57746660-ca9c1a00-76ef-11e9-94b0-461059066924.png">

**Comment by annakocheshkova** [comment] 2019-05-15 07:28
Hi @shyamjimishra1993, the `MSErrorReport` object is derived from the `PLCrashReport` - it's just the parsed report. Though you can't access the original file, you can make use of the data stored in that object.

**Comment by shyamjimishra1993** [comment] 2019-05-15 08:48
Ok, Thanks. So you mean, we don't have any way to achieve the use case I am mentioning using App Center?

**Comment by annakocheshkova** [comment] 2019-05-15 08:52
If you want the `.crash` file exactly then I don't think it's achievable using App Center. But I will wait for @clpolet to confirm if there's any workaround.

**Comment by shyamjimishra1993** [comment] 2019-05-15 09:12
@annakocheshkova 
Thanks. 

Let it get confirmed. As it could be our deciding factor to go with APPCenter SDK or look for some other alternatives.

**Comment by annakocheshkova** [comment] 2019-05-15 10:01
@shyamjimishra1993 got it. If it can't be done right now, we can always make it a feature request, so unless it's time-critical you wouldn't have to give up on App Center.

**Comment by shyamjimishra1993** [comment] 2019-05-15 10:11
Thanks @annakocheshkova 
Since we were using Hockey App rest api to upload the crash earlier.

This is what we were doing.
We integrated PLCrashReporter. It gives us the crashes. We Write it to the app directory and then upload the crash to Hockey App using the rest API which hockey app has provided to upload custom crashes. That way we had crashes on Hockey app Portal and in App directory also(Not all but few last crahses).


Since with AppCenter, We don't have any API to upload the custom crashes(I know there is a Feature request). We are left with using APP Center SDK. If we use it, we can't have PLCrashReporter along with.

Not sure how to solve this use case.




 So we had privilege to use PLCrashReporter and Get crahses from

**Comment by annakocheshkova** [comment] 2019-05-15 10:14
@shyamjimishra1993 App Center uses PLCrashReporter under the hood so I'm sure either there's a workaround or we can make a feature request.

**Comment by annakocheshkova** [comment] 2019-05-15 10:40
@shyamjimishra1993 just confirmed the behavior. You can get these raw files from the directory where `PLCrashReporter` saves them, just do it **before** App Center starts. After the start, they are processed by App Center abnd deleted.

**Comment by shyamjimishra1993** [comment] 2019-05-15 10:58
Thanks, @annakocheshkova  on this. Let me try to fetch data from the directory used by PLCrashReporter. Need to investigate on the path used by PLCrashReporter. Let me know if there is any sample app/code for this. Thanks.

**Comment by shyamjimishra1993** [comment] 2019-05-15 12:09
Hi @annakocheshkova  @clpolet ,
Thanks for helping on this.

As you mentioned that we can fetch the raw files before App Center starts. Once We start it it will be deleted.
So i could see the **"live_report.plcrash"** in a folder created by PLCrashReporter, Which is getting deleted once I start App center. So i will just copy it before it gets deleted.

My question here is, This file is encoded by PLCrashReporter. and After fetching it i need to decode it into .crash file.
For that i need to use PLCrashLibrary only. Below is how we decode it and store locally.

**plCrashFileData** is the data for the file which we copied.
 
PLCrashReportTextFormat textFormat = PLCrashReportTextFormatiOS;
    /* Decode data */
    PLCrashReport *crashLog = [[PLCrashReport alloc] initWithData: **plCrashFileData** error: &error];
    if (crashLog == nil) {
        NSLog(@"Could not decode crash file :%@",  [[error localizedDescription] UTF8String]);
    } else {
        NSString* report = [PLCrashReportTextFormatter stringValueForCrashReport: crashLog withTextFormat: textFormat];
        NSLog(@"Crash log \n\n\n%@ \n\n\n", report);

        NSString *outputPath = [documentsDirectory stringByAppendingPathComponent: @"app.crash"];
        if (![report writeToFile:outputPath atomically:YES encoding:NSUTF8StringEncoding error:nil]) {
            NSLog(@"Failed to write crash report");
        } else {
            NSLog(@"Saved crash report to: %@", outputPath);
        }

    }

Since we can't have PLCrashReport integrated with our project because it's already integrated with AppCenter SDK.

Do you see any other way to decode data from ".plcrash" to ".crash"?

**Comment by annakocheshkova** [comment] 2019-05-15 12:15
@shyamjimishra1993 I see in another thread you wanted to import App Center .xcproject instead of frameworks. If you do that way, you can just reference CrashReporter.framework in your test app.

**Comment by shyamjimishra1993** [comment] 2019-05-15 13:00
Hi @annakocheshkova ,

So you mean if we are going with framework way, Then it looks not possible to decode data from ".plcrash" to ".crash"? Correct me if I am wrong. I didn't understand your last comment fully.

**Comment by annakocheshkova** [comment] 2019-05-15 13:53
@shyamjimishra1993 sorry, I thought you were going to use the SDK by importing the `.xcodeproj` files. If you import it using frameworks, everything should work. You can use `PLCrashReporter` without any extra setup.

**Comment by annakocheshkova** [comment] 2019-05-15 14:24
@shyamjimishra1993 disregard previous message, I forgot to clean the project. Yeah, we don't export CrashReporter headers so you will have to add the headers to your project (just the headers, not the `CrashReporter.framework` - so that there were no duplicate symbols).

**Comment by clpolet** [comment] 2019-05-15 17:42
@shyamjimishra1993 building your own stringified report out of the `MSErrorReport` object properties is probably the most stable approach and doesn't involve `PLCrashReporter`.

**Comment by clpolet** [comment] 2019-05-15 18:36
But wait @shyamjimishra1993 there is actually no need in saving the whole crash report if it's sent to AppCenter. Just save the [incident Identifier property](https://github.com/microsoft/appcenter-sdk-apple/blob/d3eb6c942c39be49a6363f28c86f799eb5c1f5c0/AppCenterCrashes/AppCenterCrashes/Internals/Model/MSErrorReport.h#L13) from the `MSErrorReport` object. You can search for crashes in the AppCenter portal based the incident identifier. Simple and effective :).

**Comment by shyamjimishra1993** [comment] 2019-05-15 18:44
Thanks @annakocheshkova for your support on this.
I just added CrashReporter headers to my project(only .h files).  Getting the following issue.

<img width="679" alt="Screenshot 2019-05-16 at 12 03 47 AM" src="https://user-images.githubusercontent.com/20599875/57800217-78e6a480-776e-11e9-8e2e-5edc52ddec11.png">

Not sure why I am getting this issue. The similar kind of issue I got when I was trying to add App center using .xcproject. Really missing something here.

Yeah, you are right in your comment with using MSErrorReport and building custom reports. But If we could just get the .crash file as it is, So when a customer shares their logs with us, we will get this .crash file also and do the Symbolication and we could see the full trace for the crash.

That's the reason we want the actual .crash file rather than creating any custom crash report.

**Comment by shyamjimishra1993** [comment] 2019-05-15 18:56
Hi @annakocheshkova ,
The incident Identifier property approach sounds good. But I don't see a way to filter based on incident Identifier property. Could you plz share some screenshot of the filter you are mentioning in APP center?
<img width="1370" alt="Screenshot 2019-05-16 at 12 20 02 AM" src="https://user-images.githubusercontent.com/20599875/57801058-83a23900-7770-11e9-9d93-1d1c02949bdc.png">

Definitely App center portal helps us in many ways. but another reason for having few last crashes as part of app directory is that We could directly get Crash from the user and help them pretty quickly rather than looking into the portal and applying filters for that specific user.

**Comment by clpolet** [comment] 2019-05-16 15:53
@shyamjimishra1993 There is no need to send the full crash report in the customer bug report. If you have uploaded the symbols for your application in AppCenter and the bug report from your customer contains the incident identifiers and the SDK successfully sent the report to AppCenter then you can look up for the crashes on the AppCenter portal with the incident identifiers. You'll see the symbolicated stack trace there. Give it a try :wink:.

**Comment by shyamjimishra1993** [comment] 2019-05-17 05:17
Thanks, @clpolet . Will give it a try.

**Comment by annakocheshkova** [comment] 2019-05-20 08:20
Hi @shyamjimishra1993 did you have a chance to try?

**Comment by Jamminroot** [comment] 2019-05-28 08:55
Closing a thread, feel free to reopen if you feel like you need support.

**Closed by Jamminroot** 2019-05-28 08:55 UTC
Labels: support
