### ISSUE TITLE
Binaries are missing from 2.5.2

### ISSUE THREAD

**Issue by florianbuerger** [microsoft/appcenter-sdk-apple#1923] opened 2019-12-13 13:25 UTC
The [2.5.2](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/2.5.20) release doesn't have any binaries attached to it.

Since building from source is discouraged according to #1794 this breaks `carthage update` when not pinned to an explicit version.

Workaround for now seems to be to not allow upgrading to this version. Example `Cartfile`

```
github "microsoft/appcenter-sdk-apple" == 2.5.1
```

Please allow either building by source or add binaries to the release.

**Comment by MatkovIvan** [comment] 2019-12-13 14:19
Hi there,

We've found a critical issue in that release, so we had to remove this binary from GitHub releases page. We're working on a hotfix now, please use 2.5.1 before hotfix release.

Sorry for the inconvenience.

Duplicate of https://github.com/microsoft/appcenter-sdk-apple/issues/1918#issuecomment-565338896

**Closed by MatkovIvan** 2019-12-13 14:19 UTC
Labels: support
