### ISSUE TITLE
MSCrashesUncaughtCXXTerminateHandler

### ISSUE THREAD

**Issue by raiumarius** [microsoft/appcenter-sdk-apple#2042] opened 2020-04-28 08:31 UTC
The issue is that in the appcenter diagnostics we can see a lot of crashes that seem to be caused by appcenter itself. I saw the issue was **mentioned several times in another thread** with no answers.

We are using the latest version of the sdk and the latest version of cocoapods

`MAIN THREAD - CRASHED

libsystem_kernel.dylib
__pthread_kill
libsystem_c.dylib
abort
libc++abi.dylib
abort_message
libc++abi.dylib
demangling_terminate_handler()
libobjc.A.dylib
_objc_terminate()
APPNAME
MSCrashesUncaughtCXXTerminateHandler() MSCrashesCXXExceptionHandler.mm:160
libc++abi.dylib
std::__terminate(void (*)())
libc++abi.dylib
std::terminate()
libdispatch.dylib
_dispatch_client_callout
libdispatch.dylib
_dispatch_main_queue_callback_4CF$VARIANT$mp
CoreFoundation
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
CoreFoundation
__CFRunLoopRun
CoreFoundation
CFRunLoopRunSpecific
GraphicsServices
GSEventRunModal
UIKitCore
UIApplicationMain
APPNAME
main AppDelegate.swift:22
libdyld.dylib
start`

There are no repro steps, it seems to be happening quite randomly.

**Comment by MatkovIvan** [comment] 2020-04-28 14:53
Hi @raiumarius ,

Yeah, the similar questions were raised a few times (#2015, #1882, #1867 and a few others outside of this repository), but as mentioned before it doesn't look like SDK problem - it's caused by some C++ exception from an app.
Let me summarize the info and explain some details.

## What is `MSCrashesUncaughtCXXTerminateHandler` function?

First of all, I want to clarify what `MSCrashesUncaughtCXXTerminateHandler` function really is. It's a callback that used with [`std::set_terminate`](https://en.cppreference.com/w/cpp/error/set_terminate):
https://github.com/microsoft/appcenter-sdk-apple/blob/9cda019f382e53844f369e168fd02ad457b11c07/AppCenterCrashes/AppCenterCrashes/Internals/MSCrashesCXXExceptionHandler.mm#L191
So, it's called on uncaught exceptions when they are already thrown from somewhere. An application will be terminated after this function that stores exception details. **This function is not called anywhere aside from termination callback.**
 
## Why is it in my crash stack trace?

Ideally, you should see the stack trace to the line where the exception was actually thrown. But there are some cases where the data about original place is unavaliable:

1. An exception was thrown from another dynamic library: https://github.com/microsoft/appcenter-sdk-apple/blob/9cda019f382e53844f369e168fd02ad457b11c07/AppCenterCrashes/AppCenterCrashes/Internals/MSCrashesCXXExceptionHandler.mm#L123
2. The place where it was happened wrapped to Apple's UI library that swallows the details. See known [apple bug](https://forums.developer.apple.com/thread/116305).

When the data about original stacktrace is missed, SDK uses a fallback - where it grabs the current stacktrace, which contains the frame with this function.

___

I understand that it contains not enough data to find root issue of the problem, but it's all data that SDK can grab. At least we can say that it's some C++ exception.

I'm going to close this issue now, but feel free to reply if you have some questions here.

**Closed** 2020-04-28 14:53 UTC
Labels: question, support
