### ISSUE TITLE
Please Add Support for Swift Package Manager

### ISSUE THREAD

**Issue by cliftonlabrum** [microsoft/appcenter-sdk-apple#1865] opened 2019-11-06 22:46 UTC
Xcode 11 now has first-party support for Swift packages. Please add a Swift package manifest to this repository. 🙂

Thank you!

![spm-ac](https://user-images.githubusercontent.com/2513753/68344568-8d1bb680-00ac-11ea-8ec5-98251f84f0c2.png)

**Comment by MatkovIvan** [comment] 2019-11-08 22:38
Hi @cliftonlabrum,

Thanks for getting in touch!
It's a duplicate of recently transferred issue to AppCenter Central Repository where all the new feature requests are being tracked and prioritized.

Duplicate of https://github.com/microsoft/appcenter/issues/1295

**Closed by MatkovIvan** 2019-11-08 22:38 UTC
Labels: feature request
