### ISSUE TITLE
Duplicate interface definition for class 'MSAbstractLog.h' and 'MSServiceAbstract.h'

### ISSUE THREAD

**Issue by madhurima09** [microsoft/appcenter-sdk-apple#1734] opened 2019-08-19 17:20 UTC
Hello,

I'm trying to integrate AppCenter SDK into my project. I have added both the frameworks i.e 'App Center' and 'App Center Crashes'. Both these frameworks have 2 exactly same header files i.e 'MSAbstractLog.h' and 'MSServiceAbstract.h' , as a result of which I'm getting the below compile time errors

- AppCenter/AppCenter/MSAbstractLog.h:6:1: error: duplicate interface definition for class 'MSAbstractLog'

- AppCenter/AppCenter/MSServiceAbstract.h:14:1: error: duplicate interface definition for class 'MSServiceAbstract'

- AppCenter/AppCenter/MSServiceAbstract.h:19:35: error: property has a previous declaration

I have tried adding the frameworks once using binary integration and once via cocoapods. Both ways I got the same issue.
Also, as per the app center sdk documentation, I need to include both the frameworks App Center and App Center Crashes. 

Any one else faced same issue? 
Also, could anyone help to figure out how to resolve this problem?

Thanks.

**Comment by AnastasiaKubova** [comment] 2019-08-20 08:00
Hi, madhurima09 ! Thank you for contacting us! I didn't manage to reproduce your issue. Could you please clarify some details:
- What the version SDK are you use?
- Could you please share the code snippet with use our SDK?

**Comment by madhurima09** [comment] 2019-08-20 14:23
Hi @AnastasiaKubova 
Thanks for taking a look at this.
I'm on the latest version of app center sdk. The below implementation is in AppDelegate class.

#import <AppCenter/AppCenter.h>
#import <AppCenterCrashes/AppCenterCrashes.h>

+ (void)initAppCenterCrashService
{
    [MSCrashes setDelegate: self];
    [MSAppCenter start:@"key" withServices:@[[MSCrashes class]]];
}

+ (void)appCenterCrashReportingService
{
static dispatch_once_t onceToken1 = 0;
        dispatch_once(&onceToken1, ^{
[self initAppCenterCrashService];
}
}

To reproduce the issue
1) Once app center is installed via cocoapods or by copying the binaries. 
2)And on building the project there after, the above reported build issues start to show.

Attached is the structure of how the framework looks once installed via cocoapods.

You will notice in the attached image that both AppCenter framework and AppCenterCrashes framework has these 2 same header files'MSAbstractLog.h' and 'MSServiceAbstract.h'.
Because of which I'm running into the above mentioned compilation errors.

![Screen Shot 2019-08-20 at 9 59 50 AM](https://user-images.githubusercontent.com/16856153/63353794-4a5e0400-c331-11e9-82ad-9f564d1b9c75.png)

**Comment by hypherion2** [comment] 2019-08-20 16:53
I was having similar issues with duplicate definitions in my project and I used the following #includes instead which fixed it:

#import <AppCenter/MSAppCenter.h>
#import <AppCenterCrashes/MSCrashes.h>
#import <AppCenterCrashes/MSCrashesDelegate.h> // optional
#import <AppCenterCrashes/MSErrorAttachmentLog.h> // optional

The documentation states that one needs to use @import statements which in my case will not work since I have modules disabled in XCode project settings.

**Comment by madhurima09** [comment] 2019-08-20 19:45
Hi @hypherion2 

Yes even I can't use @import statements because of the same reason. And thanks the above imports helped resolved the issue.

**Comment by AnastasiaKubova** [comment] 2019-08-21 10:49
Hi, @madhurima09! Thank you for providing steps. I spent time to try to reproduce this issue, but I don’t have the same problem. Could you please clarify also:
- What version of Xcode do you use?
- Could you please try to reproduce this issue on an empty project and let me know about the results?

**Comment by madhurima09** [comment] 2019-08-21 13:45
Hi @AnastasiaKubova,

Thanks again for looking into this. But the issue above is pretty straight forward. In the image I attached if you notice the folder structure of both the frameworks you will see some header files are common in both which is resulting in failure. 

Also, I'm not sure if you using @import statements or #import statements.
The issue is seen persistently with #import statements of the header files I put in my code snippet above.

But anyway, using different set of imports I'm able to get pass this problem. Closing the issue.

**Comment by synalysis** [comment] 2019-09-09 10:04
> I was having similar issues with duplicate definitions in my project and I used the following #includes instead which fixed it:
> 
> #import <AppCenter/MSAppCenter.h>
> #import <AppCenterCrashes/MSCrashes.h>
> #import <AppCenterCrashes/MSCrashesDelegate.h> // optional
> #import <AppCenterCrashes/MSErrorAttachmentLog.h> // optional
> 
> The documentation states that one needs to use @import statements which in my case will not work since I have modules disabled in XCode project settings.

Can you combine MSCrashes.h with MSAnalytics.h?

Whenever I have those two header files included I still get the "Duplicate interface definition" error
```
#import <AppCenterCrashes/MSCrashes.h>
#import <AppCenterAnalytics/MSAnalytics.h>

```

**Comment by clpolet** [comment] 2019-09-12 01:28
I am reopening this issue. @synalysis is your application using ObjC++ or "modules disabled" disabled?

**Comment by synalysis** [comment] 2019-09-12 07:53
@clpolet the application uses "modules disabled" and only Objective-C and plain C, no ObjC++

**Comment by clpolet** [comment] 2019-09-17 19:25
The AC SDK doesn't support the *#import* notation, it leads to the duplicate issues seen here. It's something that can be worked around by tweaking the imports but ultimately it should be supported out of the box by the SDK so I am labeling it as a feature request.

**Comment by synalysis** [comment] 2019-09-18 06:09
@clpolet thank you, that makes sense. My workaround is to create a new class that's responsible for the analytics part and doesn't import the crash reporter header.

**Comment by TheChrisGlass** [comment] 2019-10-01 22:12
This change would help us as well, as we're migrating now and hitting this roadblock.

**Comment by synalysis** [comment] 2019-10-02 16:52
> @TheChrisGlass hitting this roadblock

As a workaround you can import the headers in different files (just create a new class that only handles crashes or analytics). Not nice and not as smooth as desired but a small jump over the roadblock.

**Comment by quzongyao** [comment] 2019-10-04 05:14
latest update on latest sdk (2.4.0)
1. Ultimately, the umbrella header could not be used, otherwise AppCenter.h , AppCenterCrashes.h and AppCenterAnalytics.h will conflict with each other due to the duplicated definition.

Currently, the WA is to include the separated module header, such as MSAppCenter.h MSCrashes.h, etc.

But still, as @TheChrisGlass said, we could not use crashes and analytics in the same time, as 

this code 

`[MSAppCenter start:
              withServices:@[MSCrashes.class, MSAnalytics.class]]`

enforce us to import  MSCrashes.h and MSAnalytics.h in the same code file.

**Comment by MatkovIvan** [comment] 2019-10-07 08:41
@quzongyao App Center doesn't enforce initializing the services in the same code file.

There are start function overloads to start services separately:
https://github.com/microsoft/appcenter-sdk-apple/blob/5e0e8105bc2553980f64fdbfc842f075ef12b76c/AppCenter/AppCenter/MSAppCenter.h#L47-L54

You can use this as temporary workaround here.

**Comment by quzongyao** [comment] 2019-10-10 03:24
As you could see in the comment,
  * @discussion This may be called only once per application process lifetime. 

If this API could be called several times, then MS should clarify it somewhere.

Since it is a Class API, we don't know how the static variables are managed inside of the SDK.

Furthermore, if this API could be called multiple times, then how the services are setup after multiple calls? 
Does SDK will always overwrite all the services? or just add new ones?

**Comment by guperrot** [comment] 2019-10-10 04:12
There are multiple methods here.

```
[MSAppCenter start: withServices:@[MSCrashes.class, MSAnalytics.class]]
```

Allows to be called multiple times but with different services each time. This variant does not have the appSecret as a parameter and is currently not documented in https://docs.microsoft.com/en-us/appcenter/ and requires appSecret to have been configured before calling it.

To go into more details, the ones that can be called only once are:

```
+ (void)start:(NSString *)appSecret withServices:(NSArray<Class> *)services;
+ (void)configureWithAppSecret:(NSString *)appSecret;
```

`+ (void)start:(NSString *)appSecret withServices:(NSArray<Class> *)services;`, the officially documented method in the getting started, is a shortcut for `+ (void)configureWithAppSecret:(NSString *)appSecret;` and then `+ (void)startWithServices:(NSArray<Class> *)services;`.

If you plan to use `+ (void)startWithServices:(NSArray<Class> *)services;` to split service starting you still need to call `+ (void)configureWithAppSecret:(NSString *)appSecret;` once before (further calls to `configureWithAppSecret` will be ignored).

**Comment by MatkovIvan** [comment] 2019-10-10 07:54
Hi @quzongyao,

The fix has been merged, so it should work with the next version (will be released this month).

**Comment by charmian01** [comment] 2019-10-17 08:31
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.

**Closed** 2019-10-17 08:32 UTC
Labels: bug
