### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by adamayoung** [microsoft/appcenter-sdk-apple#1892] opened 2019-11-21 10:33 UTC
**Describe the solution you'd like**
It would be great if you'd support Swift Package Manager.

**Comment by russelarms** [comment] 2019-11-21 11:59
Hi @adamayoung,

Thanks for getting in touch!
It's a duplicate of the recently transferred issue to AppCenter Central Repository where all the new feature requests are being tracked and prioritized.

Duplicate of [microsoft/appcenter#1295](https://github.com/microsoft/appcenter/issues/1295)

**Closed by russelarms** 2019-11-21 11:59 UTC
Labels: feature request
