### ISSUE TITLE
Live report support

### ISSUE THREAD

**Issue by marciniwanicki** [microsoft/appcenter-sdk-apple#1740] opened 2019-08-28 10:04 UTC
### **Description**
 
I think it would be very useful if `MSCrashes` offers an API to generate live reports (without triggering an actual crash condition). This helps to capture and debug certain states of applications that do not trigger crashes but affect some execution paths.

```objc
- (NSData *)generateLiveReport;
```
is already available in the `PLCrashReporter` public API. A method 

```objc
- (nullable MSErrorReport *)generateLiveReport;
```
leveraging `PLCrashReporter` API should be sufficient and relatively easy to implement.

Happy to create a PR if you think this idea is worth pushing forward.

### **Details**

1. Which SDK version are you using? 2.3.0

**Comment by Jamminroot** [comment] 2019-08-28 10:42
And again, hello, @marciniwanicki :) And, again, I'll let our PMs team look at this request, too

**Comment by marciniwanicki** [comment] 2019-08-28 10:42
Thanks @Jamminroot :) Looking forward to hear from you

**Comment by hamswan** [comment] 2019-08-30 20:51
Thanks @marciniwanicki we have added this as a feature request. You can track this here.

**Comment by Harrioson** [comment] 2019-11-27 12:10
Microsoft’s OneDrive service gives you access to store 
your files on the cloud and retrieve them whenever you need them.
https://www.techsovibe.com/how-to-access-onedrive/

**Comment by DmitriyKirakosyan** [comment] 2021-12-24 11:57
Hi @marciniwanicki , we prepared a [PR](https://github.com/microsoft/appcenter-sdk-apple/pull/2390) with the API you requested.
Could you please clarify how would you use this API? Could `trackError`/`trackExceptoin` (see [Handled Errors](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios#handled-errors)) be an alternative for your case?

I'm asking because I would like to make sure that `MSACErrorReport` is a good choice for the return type for this API.

**Comment by DmitriyKirakosyan** [comment] 2022-01-12 15:01
Since there was no confirmation that the feature request is still relevant, I'm going to close this issue and the PR.
Please reopen the issue if anyone is still interested in this feature and we will resurrect the PR.

**Closed by DmitriyKirakosyan** 2022-01-12 15:01 UTC
Labels: feature request, next-release

**Comment by marciniwanicki** [comment] 2023-07-24 07:53
Hi @DmitriyKirakosyan and @AnastasiaKubova , would it be possible to re-open and merge the PR https://github.com/microsoft/appcenter-sdk-apple/pull/2390?

**Comment by DmitriyKirakosyan** [comment] 2023-08-09 08:49
Hi @manuchandel , welcome back :) Could you answer these questions?

> Hi @marciniwanicki , we prepared a [PR](https://github.com/microsoft/appcenter-sdk-apple/pull/2390) with the API you requested. Could you please clarify how would you use this API? Could `trackError`/`trackExceptoin` (see [Handled Errors](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios#handled-errors)) be an alternative for your case?
> 
> I'm asking because I would like to make sure that `MSACErrorReport` is a good choice for the return type for this API.

**Comment by marciniwanicki** [comment] 2023-08-15 21:27
Hi @DmitriyKirakosyan, 

Thanks for getting back and sorry for the delays. Sure, happy to give you a broader context.

`generateLiveReport` allows us to capture stack trace at any given point of time. In our case, we need them when something unexpected happens within WebView (executing JavaScript).
There might be multiple reasons why something fails in web stack and we want to ensure we can get all the diagnostics possible (stack trace is one of them), i.e. when an error occurs in JavaScript, then we capture the live stack trace and log it along with the underlying error.

I had a brief at https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios#handled-errors and it does seem to be a good fit. We need the report without actually triggering any real error/exception in the native code (but perhaps I missed something).

**Comment by DmitriyKirakosyan** [comment] 2023-08-16 14:50
Hi @marciniwanicki , thank you for the reply. Glad to hear you find handled errors API useful in your case. Correct, tracking handled errors won't trigger an exception in your app.

Does it mean the issue is resolved for you now?
