### ISSUE TITLE
Add SDK support for watchOS

### ISSUE THREAD

**Issue by jrothenbacher** [microsoft/appcenter-sdk-apple#2120] opened 2020-07-02 08:07 UTC
**Is your feature request related to a problem? Please describe.**

We would like to use the App Center SDK (especially the services *App Center Analytics* and *App Center Crashes*) also on watchOS. We are using those on our companion iOS app and they give us the insights we need and value. However, on the watchOS app, this is unfortunately not possible.

**Describe the solution you'd like**

Use *App Center Analytics* and *App Center Crashes* on watchOS.

**Describe alternatives you've considered**

In order to check, if watchOS support is simply not documented, we added the Swift Package of the `SDK version 3.3.0` as dependency on the watchOS target (on `Xcode Version 11.5 (11E608c)`), but compilation failed.

**Additional context**
N/A.

**Comment by MatkovIvan** [comment] 2020-07-02 09:09
It looks like duplicate of https://github.com/microsoft/appcenter/issues/1577

**Comment by jrothenbacher** [comment] 2020-07-02 11:28
Thanks for the quick reply! This is indeed what we are looking for. Didn't expect it in the App Center repo.

Do you have any updates on this?

**Comment by MatkovIvan** [comment] 2020-07-02 13:04
Not yet. Feel free to vote in the original issue so PMs can proper triage/prioritize this.

Closing this one as it's a duplicate.

**Closed by MatkovIvan** 2020-07-02 13:04 UTC
Labels: feature request
